### ISSUE TITLE
[Feature Request] Horizontal Nav

### ISSUE THREAD

**Issue by richbryant** [BlazorFluentUI/BlazorFluentUI#103]
I know Microsoft doesn't include a Horizontal Nav in Fabric but it's commonly requested, even for them.  And it would make building sites that aren't Sharepoint/Office365 specific far easier.

What would be nice is something akin to the traditional Bootstrap NavBar, with ability to include icons and dropdown menus.

Thanks for reading!

**Comment by limefrogyank** [comment]
So like a `CommandBar` but with links/buttons that show the selected page.  That seems doable.

**Comment by richbryant** [comment]
Thanks. It would help a lot.  And be a step up on actual Fabric.

**Comment by natsuo** [comment]
Just for reference:
https://developer.microsoft.com/en-us/fluentui#/controls/web/pivot

**Comment by limefrogyank** [comment]
Well, we do have a `Pivot` already.   I think Rich wanted a different style...

**Comment by natsuo** [comment]
You are right. May I ask if the button like appearance I'm seeing in the WASM demo is intentional?
![image](https://user-images.githubusercontent.com/1655659/82073835-1ce49200-96da-11ea-943c-3753ea8c5495.png)

**Comment by limefrogyank** [comment]
Might be that the wasm demo is a little out of date.  That's a css error that I recognize.  This is what I'm seeing when running from the source code directly:
![image](https://user-images.githubusercontent.com/7821384/82074330-7378ae80-968f-11ea-976a-17f556fed348.png)

**Comment by natsuo** [comment]
That explains it. Thank you for the feedback, and sorry about not seeing the Pivot component in the demo before. I'll look into implementing the components into my project then. :)

**Comment by Eweol** [comment]
@natsuo This bug is fixed but not updated in demo 😉
It is fixed since version 3.0.1

**Comment by Eweol** [comment]
@limefrogyank Maybe we can put the version which demo page show on the demo pages
On nav for example

**Comment by limefrogyank** [comment]
@Eweol probably a good idea

**Comment by limefrogyank** [comment]
#154 
Hopefully, this looks good enough to use.  
https://www.blazorfluentui.net/navBarPage

**Comment by scsJames** [comment]
Hello
@limefrogyank How i can make background color of NavBar like Blue Please ? 
Thank you
