### ISSUE TITLE
BlazorFabric List (view details sample)

### ISSUE THREAD

**Issue by sowsan** [BlazorFluentUI/BlazorFluentUI#106]
Any samples on how to implement the binding with BlazorFabric List and redirect the user to a detail page upon click on each item (with an item Id )?

**Comment by limefrogyank** [comment]
@sowsan Just what we have shown.  You can put the List into a LayoutComponent like we did for the Nav menu if you want true navigation.  Otherwise, just generate a RenderFragment yourself.
