### ISSUE TITLE
Prefix Component-Names

### ISSUE THREAD

**Issue by Eweol** [BlazorFluentUI/BlazorFluentUI#118]
What do you think about changing component names and prefix them with "BF" or something like that to work around failures like [this](https://github.com/limefrogyank/BlazorFabric/issues/117)?

**Comment by limefrogyank** [comment]
I am ok with it for components that share names.  That's part of the reason I was creating a `BasicList` before I scrapped the refactoring.  `List` overlaps with the all important `System.Collections.Generic.List`.   Maybe a BFList would be ok.  I think doing it for all components would be too much.

**Comment by Eweol** [comment]
intension to do it on all components was from my side, that you everytime see which of the components you use are form BlazorFabric and which ones comes from other Frontend-libs

**Comment by limefrogyank** [comment]
What if we just simplified the namespace to BF so it's easy to type? Then everything can be `BF.List`? 

Hmm, that would be just as bad I guess.  If you want to do it, go ahead... but it will be a lot of work :)  Changing the project names, folder names, etc.

**Comment by limefrogyank** [comment]
Do you know why that <Text> component was unrecognized?  Was it another UI library that also used a Text component?  If so, that's not really our fault.  It's more like a C++ problem where you've added too many #include <headerfiles> statements .

**Comment by Eweol** [comment]
f work is the only mess you have with this change than I will do it 🤣
I think it is a change which make such things lot easier. 
But I will do it for V3.X if you agree 😉

**Comment by Eweol** [comment]
It is from Blazor itselfe
They also have a Text-Component in Blazor base implementation

**Comment by limefrogyank** [comment]
@Eweol Ok, I agree.

**Comment by Eweol** [comment]
#117

**Comment by limefrogyank** [comment]
This has been finished.
