### ISSUE TITLE
Weird typescript issue

### ISSUE THREAD

**Issue by limefrogyank** [BlazorFluentUI/BlazorFluentUI#121]
So it seems my typescript is not as good as I thought.  I've been using the following to add a namespace and its contents to window:
```
interface Window {
    BlazorFabricFocusZone: typeof BlazorFabricFocusZone
}
window.BlazorFabricFocusZone = BlazorFabricFocusZone;
```
And it works fine when debugging locally in server-side blazor.  But once I publish this to Azure, I don't see any errors in the console, but none of the code is being run... or at least, I can't hit a breakpoint and the code is not working.  FocusZone is the main example.  Suddenly, when published, none of the focus rectangles will move with cursor keys.

I changed it back to this:
```
(<any>window)['BlazorFabricFocusZone'] = BlazorFabricFocusZone || {};
```
And suddenly it works!  Hmmm... I can't tell the difference.  But we should keep this in mind for other bugs on the server.

**Comment by vnbaaij** [comment]
We are using JS Isolation now. No more putting stuff on the global scope.
