### ISSUE TITLE
DropDown show key instead of text in Textbox

### ISSUE THREAD

**Issue by Eweol** [BlazorFluentUI/BlazorFluentUI#122]
If Text and Key are different in BFUDropDownItem the Callout show right values but selected is Key instead of Text so "wrong" value is shown

Best way to solve is Create interface with key and Text and move this from Item to parent.
parent only accept the Interface

**Comment by limefrogyank** [comment]
See if this version of Dropdown is acceptable:
https://github.com/BlazorFluentUI/BlazorFluentUI/tree/refactor/Dropdown

**Comment by limefrogyank** [comment]
Fixed with recent commit: 
https://github.com/BlazorFluentUI/BlazorFluentUI/commit/e082db4b46b3c8c50b54eaa158a7394672133bcd
