### ISSUE TITLE
Client-side instructions are wrong for 3.2.0-preview3

### ISSUE THREAD

**Issue by limefrogyank** [BlazorFluentUI/BlazorFluentUI#123]
Need to redo them... possibly update the demo

**Comment by Eweol** [comment]
Why redo them?
I think they need to be extended to support Program.cs instead of Startup.cs or is there something else?
If not I will do that today

**Comment by Eweol** [comment]
@limefrogyank,
Is it fixed with latest push to ReadMe?

**Comment by limefrogyank** [comment]
That looks good.  I was also referring to the wiki:
https://github.com/BlazorFluentUI/BlazorFluentUI/wiki/Installation-&-Basic-Usage

**Comment by Eweol** [comment]
> That looks good. I was also referring to the wiki:
> https://github.com/BlazorFluentUI/BlazorFluentUI/wiki/Installation-&-Basic-Usage

Hey @limefrogyank,
Is also Done.
please have another look at it and if it fits pls close the issue.

**Comment by limefrogyank** [comment]
Looks good!  Thanks!
