### ISSUE TITLE
Trouble starting up

### ISSUE THREAD

**Issue by Astn** [BlazorFluentUI/BlazorFluentUI#126]
I'm running  dotnet.3.2.0-preview5.20216.1 and I'm just trying to get setup and running.

I've tried to follow the readme, and things go O.K. until I add a control to one of my pages.

Here is my setup.

Index.html
```
...
    <style id="staticcs"></style>
</head>
...
    <script src="_framework/blazor.webassembly.js"></script>
...
    <script src="_content/BlazorFabric.BaseComponent/blazorFabric.min.js"></script>
```

Progam.cs
```
...
            builder.Services.AddBlazorFabric();
            builder.RootComponents.Add<App>("app");
            builder.RootComponents.Add<GlobalRules>("#staticcs");
...
```

App.razor
```
<FabricTheme>

        <Router AppAssembly="typeof(Program).Assembly" >
            <Found Context="routeData">
                <ResponsiveCascader>
                    <RouteView RouteData="routeData" DefaultLayout="@typeof(MainLayout)" />
                </ResponsiveCascader>
            </Found>
            <NotFound>
                <p>Page not found.</p>
            </NotFound>
        </Router>

</FabricTheme>
```

MainLayout.razor
```
...
@* It runs fine until I add a component to the page like a button *@
        <DefaultButton Toggle="true"
                       Checked="@(UseDarkTheme)"
                       Text="@(UseDarkTheme ? "Use Light Theme" : "Use Dark Theme" )"
                       IconName="@(UseDarkTheme ? "Volume0" : "Volume3")"
                       OnClick="@SwitchTheme"
                         />
```

![image](https://user-images.githubusercontent.com/6857743/80339677-6a2cbc80-881c-11ea-947c-d6bd6a113c68.png)

Any ideas what I'm missing?

**Comment by Astn** [comment]
Just saw this commit. Maybe it's the issue I'm hitting?
https://github.com/BlazorFluentUI/BlazorFluentUI/commit/9d1a5115ebe908db27289efa0e3d3f4708c9859c

**Comment by Eweol** [comment]
Hey @Astn,
Yes this is the issue.
everything should work work quiet fine even if you get this errors.
Sorry for that

**Comment by Astn** [comment]
Thanks for the speedy reply @Eweol 
I'm looking forward to using this project!

**Comment by Eweol** [comment]
if you have some other issues pls ping ;-)
