### ISSUE TITLE
Something up with the callbacks on dotnet.3.2.0-preview5.20216.1

### ISSUE THREAD

**Issue by Astn** [BlazorFluentUI/BlazorFluentUI#129]
Not sure if it's something I've got with my setup, or what, but every lambda I setup with BlazorFluent gives me compile errors until I manually create a converter.

eg this is what I have to do
```
<Panel 
   Type=@PanelType.SmallFixedNear 
   OnDismiss=@(new EventCallback(this, (Action<bool>)((b) => isPanelOpen = false))) 
   IsOpen="@isPanelOpen" IsLightDismiss="true">
```

where I would expect it to be

```
<Panel 
   Type=@PanelType.SmallFixedNear 
    OnDismiss=@(b => isPanelOpen = false) 
    IsOpen="@isPanelOpen" IsLightDismiss="true">
```

![image](https://user-images.githubusercontent.com/6857743/80802752-75118500-8b6d-11ea-9527-a107cf36cef5.png)

And it's this way with every control.

**Comment by Eweol** [comment]
I will have t a look at it this evening (CET) 
But for me it's working also in preview5

**Comment by Eweol** [comment]
Hey @Astn ,
I currently also create an app with help of Blazorfluent in dotnet.3.2.0-preview5.20216.1 and I copied only your snipped out of the github issue and inclueded in a Component and it work fine from very beginning

If I run into some problems like this which don't make sense I clean hole solution and close Visual Studio than reopen and Build again.
After that most stuff work again.

**Comment by Astn** [comment]
Thanks I'll mess around with my setup and see if I can make it happy.
