### ISSUE TITLE
Illegal nested style

### ISSUE THREAD

**Issue by hez2010** [BlazorFluentUI/BlazorFluentUI#130]
Add the GlobalRules component to head tag inside index.html:
```html
<style id="staticcs"></style>
```

It will finally generate:
```html
<style id="staticcs">
  <style>
    ....
  </style>
</style>
```

Which is illegal for style tag cannot be nested.

**Comment by Eweol** [comment]
Hey @hez2010,
Jup you are right this is illegal and only a workaround for now.
The Problem here is that ServerSide-Blazor needs the additional style tags because there it works a little different.
I will try to solve this problem up to next release.
