### ISSUE TITLE
Point between Nav items if not in NavLinkGroup

### ISSUE THREAD

**Issue by NPadrutt** [BlazorFluentUI/BlazorFluentUI#135]
I tried to create a couple of Nav items and noticed that there is always a point between them. After some experimentation I noticed that this is only the case if you don't have them in a NavLinkGroup.

![image](https://user-images.githubusercontent.com/1764367/81565123-22b83b80-9399-11ea-929c-a24d39d67af4.png)

```
<Nav>
        <Nav>
            <NavFabricLink Name="@localizedStrings.DashboardMenuTitle" Url="" Icon="ViewDashboard" Id="/" />
            <NavFabricLink Name="@localizedStrings.StatisticsTitle" Url="Statistics" Icon="AreaChart" Id="Statistics" />
            <NavLinkGroup Name="@localizedStrings.AdministrationMenuTitle" CollapseByDefault="false">
                <NavFabricLink Name="@localizedStrings.CustomerManagementMenuTitle" Url="Customers" Icon="People" Id="Customers" />
                <NavFabricLink Name="@localizedStrings.AdministrationMenuTitle" Url="Administration" Icon="Settings" Id="Administration" />
            </NavLinkGroup>
        </Nav>
```

It seems to me as if the <li> isn't completly overwritten when not wrappen in the NavLink Group

**Comment by limefrogyank** [comment]
Yeah, this is by design.  When I made this component, I copied the functionality of the react component as much as possible.
https://developer.microsoft.com/en-us/fluentui#/controls/web/nav

The only data that a `Nav` accepts in the react version is an array of groups.  So in the Blazor version, the child of a `Nav` has to be `NavLinkGroup`.  Then `NavFabricLink` will be the child of `NavLinkGroup`.  (BTW, NavFabricLink is named that way because NavLink was already taken by Blazor.)

**Comment by NPadrutt** [comment]
aah, I see. thanks for the explanation :)
Also.. I noticed that when I start a debug build and the site loads it it takes like a second before the style is applied to the nav elements. I didn't notice that on your testsite. Do you know if that is just someting in debug or might there be a performance bottleneck?

**Comment by limefrogyank** [comment]
It's a by-product of our eliminating all css files and loading styles within the components.  The workaround was to implement `IHasPreloadableGlobalStyle` and use a `StylePreloader` component to load the style in the `OnInitialized` portion of the lifecycle before the component gets actually rendered.  You can see an example of it in the `Dialog` component.  We just haven't gotten around to doing this for all the components yet.  

For `Nav`, once we implement `IHasPreloadableGlobalStyle`, we'd put the `StylePreloader` in the root layout before the `Nav` component.  Maybe I can do it now...

In any case, when .NET5 is released, theoretically, we can use css isolation and not have to use our method of loading styles anymore.

**Comment by NPadrutt** [comment]
Aah, I see. Thanks for the explanation. :)
