### ISSUE TITLE
BlazorFabric.Dropdown Nuget package seems to be missing dependencies 

### ISSUE THREAD

**Issue by MarkIannucci** [BlazorFluentUI/BlazorFluentUI#136]
Thank you for your work on this.  My initial use of BlazorFabric was to try to get a drop down to work, so I added the BlazorFabric.Dropdown package to my project and when I loaded my page, the app threw an exception `LayerHost is not present`, so I added BlazorFabric.Layer to my project and I got past that exception.

Unfortunately the DropDown still doesn't work.  I noticed that BlazorFabric.TextField lists a few other packages as dependencies, so I'm going to add those to my project and see if I can get past this problem.  If I do, I'll see if I can figure out how to submit a PR to close this issue.

**Comment by Eweol** [comment]
Can you pls share your App.razor?
I think you also forget to insert the FabricTheme-Tag which is needed.
for further information you can have a look into the ReadMe file.
The most steps of the installation guide there are required to work with Blazorfluentui.

**Comment by MarkIannucci** [comment]
Thanks for piping up!

App.Razor follows 

```
<FabricTheme>
    <StylePreloader LoadAllComponents="true" />
    <LayerHost Style="display:flex; flex-direction: row;width:100vw;height:100vh;overflow:hidden;">
        <Router AppAssembly="@typeof(Program).Assembly">
            <Found Context="routeData">
                <RouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)" />
            </Found>
            <NotFound>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p>Sorry, there's nothing at this address.</p>
                </LayoutView>
            </NotFound>
        </Router>
    </LayerHost>
</FabricTheme>
```

**Comment by Eweol** [comment]
@MarkIannucci Np
Do you also include addBlazorFabric in startup / program.Cs?

**Comment by MarkIannucci** [comment]
I did.  It is the last line in `ConfigureServices`.

**Comment by MarkIannucci** [comment]
Adding  `<component type="typeof(GlobalRules)" render-mode="ServerPrerendered" />` to my `_Host.cshtml` did start throwing an error in my project:

    `The type or namespace name 'GlobalRules' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by Eweol** [comment]
Did you add '@namespace BlazorFabric.Demo.ServerSide.Pages' on top of _Host.cshtml?

**Comment by Eweol** [comment]
GlobalRules should live in "BlazorFabric" namespace!

**Comment by MarkIannucci** [comment]
I already had a `@namespace` reference at the top of my file and you're only allowed one, so I added in an '@using BlazorFabric` directive instead.  Doing that worked :)  Thank you for your help!

**Comment by Eweol** [comment]
@MarkIannucci sry my faulire not namespace I mean '@using BlazorFabric'
SRY

**Comment by Eweol** [comment]
Ah OK you found it on your own
Than everything is fine I think
I will close
