### ISSUE TITLE
DetailsList Items not visible until window is resized

### ISSUE THREAD

**Issue by NPadrutt** [BlazorFluentUI/BlazorFluentUI#142]
I created a Detailslist according to the demo page. Now when the page is loaded, I can see that there are items in the list, but no text is shown:

![image](https://user-images.githubusercontent.com/1764367/82156091-6cad8f80-9879-11ea-9aff-fa28094943fe.png)

Although as soon as I resize the window it appears:

![image](https://user-images.githubusercontent.com/1764367/82156106-7df69c00-9879-11ea-9389-49415b027a71.png)

Do I have to do something particular to make that work without the manual resize?

**Comment by NPadrutt** [comment]
I figured it out. I was using a Stack, but didn't have the `Style="height:100%;"` in. Either by adding this or removing the stack it works.

**Comment by limefrogyank** [comment]
This is one of the reasons i hate HTML: Document based layout rather than.... Window-based? I don't know what to call app-centric layouts.
