### ISSUE TITLE
Max width of Panel is set with vh instead of vw.

### ISSUE THREAD

**Issue by sonntag-philipp** [BlazorFluentUI/BlazorFluentUI#143]
Hello there,

first of all, thank you for the realization of the fluent ui in Blazor. It really helps me with my project. 

I've got a really small problem containing the max width of your panel component.
For my use case it's necessary to set the width of your Panel container to 100vw. 
I can't do this because the max width is internally set to 100vh.

```
.ms-Panel--custom .ms-Panel-main {
    max-width: 100vh;
}
.ms-Panel--customLeft .ms-Panel-main {
    right: auto;
    left: 0;
    max-width: 100vh;
}
```

I don't think this behaviour is wanted, so I changed it locally. It's not documented how contributions are handled in this specific repository, but I can create a pull request if you want ^^

LG

Philipp

**Comment by sonntag-philipp** [comment]
Created a pull request here: https://github.com/BlazorFluentUI/BlazorFluentUI/pull/144

**Comment by Eweol** [comment]
@sonntag-philipp Thank you
Will hopefully have time this evening to verify and pull/merge it

**Comment by sonntag-philipp** [comment]
Thank you for the merge. 👍

**Comment by Eweol** [comment]
@sonntag-philipp yw

**Comment by sonntag-philipp** [comment]
@Eweol I think this fix was overriden by the renaming issue, or is this wanted behaviour?

Here are links to the relevant lines of the panel:
https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/src/BlazorFluentUI.BFUPanel/BFUPanel.razor.cs#L560
https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/src/BlazorFluentUI.BFUPanel/BFUPanel.razor.cs#L571

**Comment by Eweol** [comment]
@sonntag-philipp Could be
Will solve it again this evening (CET) 😉
Sry for that

**Comment by sonntag-philipp** [comment]
That would be very nice, thank you :D Have a nice day ^^

**Comment by Eweol** [comment]
sry was first time fixed on wrong branch.
Now it is available on master so should be in next release ;-)
