### ISSUE TITLE
Use github releases 

### ISSUE THREAD

**Issue by NPadrutt** [BlazorFluentUI/BlazorFluentUI#145]
Currently the release notes are all gathered in the readme. I would suggest that for current releases to create a release here in the repository and put the release notes there. That would free up the ReadMe quite a bit and would leave more space for the general information like how to get started. Also this would play nicely with the "Watch - Releases only" option.

**Comment by limefrogyank** [comment]
OK, I've got the latest one in releases.  Not sure what to do about all of the old stuff.  I'd like to archive it somewhere... maybe the wiki.
