### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by al-n** [BlazorFluentUI/BlazorFluentUI#148]
There's a typo in the README file in section "To use", step 6:

It actually reads:
```c#
public void Configure(IComponentsApplicationBuilder app)
{
	...;
	app.AddComponent<GlobalRules>("#staticcs");
	...;
}
```

Whereas it **should be** (notice that it's "#statics" not "#static**c**s"
```c#
public void Configure(IComponentsApplicationBuilder app)
{
	...;
	app.AddComponent<GlobalRules>("#statics");
	...;
}
```

**Comment by al-n** [comment]
Oh actually, this is only a problem when one uses the header from the Demo app, where it reads "#statics" and not "#staticcs".

You may decide to leave it as is or to change all mentions of "staticcs" in the README I gues...

**Comment by limefrogyank** [comment]
I think staticcs was supposed to be it.  i.e. Static cascading styles.  I'll make the change.  Thanks!

**Comment by limefrogyank** [comment]
> Oh actually, this is only a problem when one uses the header from the Demo app, where it reads "#statics" and not "#staticcs".

I can't seem to find this... 
I can see it just fine here in the clientside html:
https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/Demo/BlazorFabric.Demo.ClientSide/wwwroot/index.html#L27

**Comment by al-n** [comment]
Oh no, I am very sorry - misread it every time now... 
You are right, it is "#staticcs" consistently across the README and the source files, I was just mixing lines that I "copied" by typing myself and then misspelling it with lines that I copied directly... So if this is common naming in web dev I gues you should leave it - or mention that it is supposed to be like that. Only thing to think about would be how many people run into similar problems as I did...

**Comment by limefrogyank** [comment]
Maybe a small warning next to that section?  But ok, it's nice to know that something is correct still.  The recent merge broke a few things...
