### ISSUE TITLE
Client side demo broken

### ISSUE THREAD

**Issue by StevenRasmussen** [BlazorFluentUI/BlazorFluentUI#150]
Looks like the client side demo site broke after the renaming branch was merged yesterday. It's not finding the majority of the dlls:
![image](https://user-images.githubusercontent.com/11198735/82730458-17301300-9cbd-11ea-8611-a1483935c936.png)

**Comment by limefrogyank** [comment]
I might switch over to the newer Azure Static Web apps site.  The name is uglier, but the site will auto-update after every commit to master.  Might have to buy a domain...

Let me see if I can get the older version working though

**Comment by limefrogyank** [comment]
I'm not going to bother fixing the github pages website.  It works in Azure Static Pages and the new domain name is convenient.  It's now at:
https://www.blazorfluentui.net/
