### ISSUE TITLE
AllComponents NuGet seems to be missing some things

### ISSUE THREAD

**Issue by NPadrutt** [BlazorFluentUI/BlazorFluentUI#153]
When I add the "AllComponents" package I get a lot messages like of "`Microsoft.JSInterop.JSException: Could not find 'BlazorFluentUiBaseComponent' in 'window'.`" and "`Could not find 'BlazorFluentUiFocusTrapZone' in 'window'.`" messages.
I think one problem is the FocusTrapZone.js. When I add the packages manually I have this file in the solutions explorer as a file. With the "AllComponents" package i don't see that file.

**Comment by limefrogyank** [comment]
@NPadrutt Sorry about that.  I didn't test it after creating it.  Let me figure it out...

**Comment by limefrogyank** [comment]
I changed how I made the AllComponents package and tested it with locally created packages.  Hopefully, it will work the same way when downloaded from Nuget.

**Comment by limefrogyank** [comment]
I uploaded the 3.1.1 version of AllComponents to Nuget this morning. I'm not sure why I didn't upload that one before...

**Comment by NPadrutt** [comment]
@limefrogyank  3.1.1 works, thanks :)
