### ISSUE TITLE
Unhandled exception rendering component: Object of type 'BlazorFluentUI.BFUTextField' does not have a property matching the name 'valueChanged'.

### ISSUE THREAD

**Issue by herrozerro** [BlazorFluentUI/BlazorFluentUI#156]
I just installed this library (3.1.1) into my client hosted blazor site (v3.2.0).  I followed the instructions on the main readme and when I went to add a textarea like so: <BlazorFluentUI.BFUTextField AutoAdjustHeight="true" @bind-value=@Cypher.Effect Multiline="true"></BlazorFluentUI.BFUTextField>

I even simplified it to: <BlazorFluentUI.BFUTextField @bind-value="Cypher.Effect"></BlazorFluentUI.BFUTextField>

I get the above error when navigating to the page.

Am I missing something?

**Comment by limefrogyank** [comment]
Should be `@bind-Value=@Cypher.Effect`.  (Capital V)  Also, since the property's name is `Value`, when you use @bind on it, blazor automatically looks for a callback called `ValueChanged`.  We do not have that... because input boxes in html have two events:  onchange and oninput.  So instead we have the callbacks `OnChange` and `OnInput`.  (One fires on every keypress, the other fires on blur events... I always forget which is which)

So you have to tell blazor which one to use with the syntax `@bind-Value:event="OnChange"`  or the other one.

**Comment by limefrogyank** [comment]
We should make one of them the default now that I think about it.

**Comment by herrozerro** [comment]
Thanks, I'm kicking myself over the capitalization, I must have gone over the examples in the repo a half dozen times!

On another note, is there a way to get it to autoresize on render?  I have a use case that could load a bit of text and the textbox is one line by default.

**Comment by limefrogyank** [comment]
Yes, look under TextField Multiline... there's an auto-adjusting height feature.  
`Multiline="true" AutoAdjustHeight="true"`

**Comment by herrozerro** [comment]
Ah, once again I didn't go far enough, I had my simple version in the app and had the one with those properties commented out.  Thanks for your help!

**Comment by limefrogyank** [comment]
👍

**Comment by herrozerro** [comment]
Actually, I just wanted to ask about the auto-sizing.  I've got 5 lines of text, on initial load only three show.  After clicking into the textbox it expands.

Pre Click
![PreClick](https://user-images.githubusercontent.com/2041213/83364539-8fef3900-a367-11ea-94c0-fe8bae841a27.PNG)

Post Click
![PostClick](https://user-images.githubusercontent.com/2041213/83364540-92519300-a367-11ea-8449-d9f3ecf99898.PNG)

**Comment by limefrogyank** [comment]
Ok, I was wondering if that would work... I'll take a look and see if I can push a quick fix later today.

**Comment by herrozerro** [comment]
Should I open up a new issue instead of this one?

**Comment by limefrogyank** [comment]
Ah, maybe that would make tracking it easier.  Yes, do that.
