### ISSUE TITLE
Multi-Line TextField Doesn't auto resize on render

### ISSUE THREAD

**Issue by herrozerro** [BlazorFluentUI/BlazorFluentUI#158]
I have a multi-line text field with 5 lines of text, but when the page renders only three lines show, but when I click into the field it resizes.

Pre Click
![PreClick](https://user-images.githubusercontent.com/2041213/83364659-73073580-a368-11ea-8e2a-40dc32e85411.PNG)

Post Click
![PostClick](https://user-images.githubusercontent.com/2041213/83364661-74d0f900-a368-11ea-870a-13868b320a56.PNG)

If it's possible to have it render the full text when the page initializes, that would be great!

**Comment by limefrogyank** [comment]
Fixed with https://github.com/BlazorFluentUI/BlazorFluentUI/commit/29d05fa40f3634ab942cb93fb1088520e7f7eb2b
