### ISSUE TITLE
BFUTextField binding problem

### ISSUE THREAD

**Issue by ralphbecket** [BlazorFluentUI/BlazorFluentUI#162]
I'm trying to use BlazorFluentUI and am hitting problems (I'm using BlazorFluentUI.AllComponents (3.1.1) from NuGet).  I have a simple page like this:
```
@page "/"
@using BlazorFluentUI
<BFUTextField @bind-Value=xyz/>
@code {
  public string xyz = "";
}
```
When I run my application, I get an error page with the following: `InvalidOperationException: Object of type 'BlazorFluentUI.BFUTextField' does not have a property matching the name 'ValueChanged'.`  As far as I can see, I'm doing the same thing as your [demo page](https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/Demo/BlazorFluentUI.Demo.Shared/Pages/TextFieldPage.razor) code.

Am I doing something wrong or is this a problem with the library?  Many thanks in advance for any help.

**Comment by limefrogyank** [comment]
Try upgrading to 3.1.2.  I pushed a change recently that added a default `ValueChanged` EventCallback.  We didn't have it before because we wanted people to choose between oninput and onchange events, but decided we needed a default.  So it defaults to onchange.  

If you don't want to upgrade right now, a quick fix is to add:
```
@bind-Value:event="OnChange" 
```
or
```
@bind-Value:event="OnInput" 
```

**Comment by ralphbecket** [comment]
Brilliant, thanks a million!  I couldn't see anything in the code regarding having to specify a change event and the various on-line tutorial sites I've read all talk as though @bind-Value should "just work".  Thanks again, I can confirm this works now.

**Comment by limefrogyank** [comment]
Yeah, anytime you see a @bind-Something, there has to be an `EventCallback SomethingChanged`.  It literally looks for the name of the property with `Changed` tacked on it unless you specify your own @bind-Something:event="AnotherCallbackName".

Just one of the Blazor things to learn.
