### ISSUE TITLE
Button on BFUDetailsList

### ISSUE THREAD

**Issue by Proudloaf** [BlazorFluentUI/BlazorFluentUI#166]
Hi
As a C# dev new to WASM and FluentUI so far I'm loving both.
However whilst porting my basic bootstrap to FluentUI I'm having issues adding buttons to rows on BFUDetailsList.  I thought I'd be able to do something with RowTemplate like:
```
        <BFUDetailsList ItemsSource="ReadonlyList"
                        IsVirtualizing="isVirtualizing"
                        Compact="isCompact"
                        Columns="ReadonlyColumns"
                        LayoutMode="DetailsListLayoutMode.Justified"
                        @bind-Selection="selection"
                        SelectionMode="SelectionMode.Multiple">
            <RowTemplate Context="context">
                <BFUTextField Label="My Display Name"
                          @bind-Value=@context.DisplayName/>
            </RowTemplate>
 </BFUDetailsList>
````
That to display text obviously rather than a button. But nothing gets displayed at all. Am I going about this all wrong? Should I perhaps be adding a BFUDetailsRowColumn somehow?

**Comment by limefrogyank** [comment]
That should work.  One of the reasons it may not work is that you need to place it inside a container that has a height set or that is automatically set to fill the window.  This is why in the demo, I have it inside a <BFUStack> that has it's height set to 100%.

However, if you just want to display a list of buttons, you might be better off using the basic <BFUList> .  There might be less overhead.  `<BFUDetailsList>` can have its RowTemplate overridden like you did, but it's meant to use `<BFUDetailsRow>` and that's what it uses by default.  The `<BFUDetailsRow>` lets you display your data in columns and have the headers be clickable, resizable, etc.

Now, as far as customizing the contents of each cell in the `<BFUDetailsRow>`, you should be able to do it in the `ColumnItemTemplate` of the `DetailsRowColumn`.  I haven't tried it yet, but it looks wired up correctly.

Please be aware that DetailsList performance in wasm Blazor is not great when you're rendering a lot of items, even virtualized.

**Comment by limefrogyank** [comment]
Now that I think about it... it's possible it won't work properly when using a different `RowTemplate`.  Internally, `BFUDetailsList` has to measure the width and create columns that fit all the data and fit the screen.  I'm not sure if that works when there's no `BFUDetailsRow`...

**Comment by Proudloaf** [comment]
Thanks, I naively thought, that's ok I'll roll my own based on BFUDetailsRow - then I looked at the source. I still have a lot to learn!
I'm using this as a sign that I should break out of my thick client habits, stop using ListViews and be more creative with my UIs! Thanks for your help.

**Comment by limefrogyank** [comment]
Looks like it was a bug in `BFUDetailsRowField`:

https://github.com/BlazorFluentUI/BlazorFluentUI/issues/167

It's been fixed, but hasn't been added to Nuget yet.
