### ISSUE TITLE
ColumnItemTemplate in DetailsList doesn't work

### ISSUE THREAD

**Issue by thechosenone786** [BlazorFluentUI/BlazorFluentUI#167]
Hi, I am having a problem getting `ColumnItemTemplate` to work. I tried using the code below:
```csharp
new BFUDetailsRowColumn<RelatedDocumentDto>("ID", rd => rd.Id)
{
    ColumnItemTemplate = item => builder =>
    {
        builder.OpenElement(0, "span");
        builder.AddAttribute(0, "data-test", item);
        builder.AddContent(1, item);
        builder.CloseElement();
    }
}
```
but it doesn't seem to work, the row field has no content.

I'm new to Blazor so I might be missing something but I checked the source and I believe there's a missing @ symbol in front of `column.ColumnItemTemplate(column.FieldSelector(Item));` inside the `BFUDetailsRowFields.razor` file. I tried cloning the repo and adding the @ and then it seems to work. Is this just bug or am I doing something wrong?

**Comment by limefrogyank** [comment]
I'll check it out.  Normally, you can write razor code right after an if statement's braces.

**Comment by limefrogyank** [comment]
> I'll check it out. Normally, you can write razor code right after an if statement's braces.

No, that's my mistake.  There should either be an @ symbol like you said or I should tack on a (__builder) at the end.

I'll update it and it will go out in the next batch of Nuget updates.
