### ISSUE TITLE
BFUDropdown - Key, Text, OnChange

### ISSUE THREAD

**Issue by RicardoValero95** [BlazorFluentUI/BlazorFluentUI#172]
Hi!

I'm new to Wasm and Blazor. I love the components so far, they're fairly easy to use. 
Also, this is the first time I open an issue in Github. So I'd appreciate any kind of feedback 😄.

I'm making a form to create new employees. I considered using a dropdown and attempt to bind the department Id. 
Did I use **OnChange** correctly? Or is there a better way? 
Is it possible to display the **Text** in the dropdown placeholder instead of the **Key**?

Here is part of the code: 
```
<BFUDropdown Label="Departamento"
        Placeholder="Seleccionar un departamento..."
        ItemsSource=@departmentDropdownList
        OnChange=@((BFUDropdownChangeArgs args) 
                => { employee.DepartmentId = Convert.ToInt32(args.Key); }) />

@code {
        protected async override Task OnInitializedAsync()
        {
            departmentDropdownList = departmentList
                .Select(x => new BFUDropdownOption {
                    Key = x.Id.ToString(),
                    Text = x.Name,
                    ItemType = SelectableOptionMenuItemType.Normal
                }).ToList();

            await base.OnInitializedAsync();
        }
}
```

The list is fine but the placeholder shows the Key. 😥
![Annotation 2020-06-13 005854](https://user-images.githubusercontent.com/55701657/84561332-182ef000-ad11-11ea-8bd8-1414bcd42dd8.png)

Don't know if this is useful for context: 
```
        public class Employee
        {
            public int Id { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public int Number { get; set; }
            public int DepartmentId { get; set; }
            // Other properties...
        }

        public class Department
        {
            public int Id { get; set; }
            public string Name { get; set; }
            // Other properties...
        }

        public Employee employee = new Employee();
        public List<Department> departmentList = new List<Department>();
```

I have installed BlazorFluentUI.AllComponents -Version 3.1.3.3

**Comment by limefrogyank** [comment]
Sorry about that. I thought we had fixed that problem. Maybe I created the interface but forgot to fix the UI part. I'll look tomorrow and create some new Nuget packages.

**Comment by limefrogyank** [comment]
It should be fixed now.  There's a big change:  you can't use SelectedKey (and SelectedKeys) anymore.  You must use SelectedOption or SelectedOptions.  The demo page shows how the changes can be implemented.  

https://www.blazorfluentui.net/dropdownPage

(Give it a minute or two to update the demo.)

https://github.com/BlazorFluentUI/BlazorFluentUI/commit/55ff0827b50a702dcfd0e5866c5f986f9bac3d44

**Comment by limefrogyank** [comment]
FYI, I'm creating the Nuget packages and will upload them in a few minutes.

**Comment by limefrogyank** [comment]
You can definitely use `OnChange`.  The `Key` property in `BFUDropdownChangeArgs` will not work properly anymore.  Switch to using `Option` property and check for the Key or Text.

**Comment by RicardoValero95** [comment]
That sure was quick! I'm using SelectedOption and Option like you mentioned. So far it works great. Here's what I ended up doing: 
```
<BFULabel Disabled="Disabled">Departamento</BFULabel>
<BFUDropdown Label=""
        Placeholder="..."
        Disabled="Disabled"
        ItemsSource=@departmentDropdownList
        OnChange=@((BFUDropdownChangeArgs args) => 
                employee.DepartmentId = Convert.ToInt32(args.Option.Key))
        SelectedOption=@(departmentDropdownList
                .FirstOrDefault(x => x.Key == employee.DepartmentId.ToString())) />
```

![Annotation 2020-06-13 202459](https://user-images.githubusercontent.com/55701657/84582626-24b85480-adb4-11ea-9fd3-cd955e5b657c.png)

Had to create a separate label for the dropdown because **only** the label won't render as disabled. 
I used the SelectOption to select the corresponding option in case the object had already a department Id.
Just wanted to share my take on this hoping it helps somebody else.
Thanks a lot! 😃
