### ISSUE TITLE
BFUCompoundButton with Primary="true" not loading proper styles when loaded by itself.

### ISSUE THREAD

**Issue by Matthewsre** [BlazorFluentUI/BlazorFluentUI#173]
The following will not be styled correctly on its own:

`<BFUCompoundButton Text="Primary" Primary="true" SecondaryText="This is the secondary text." OnClick=@(() => OnClickHandler("Compound Primary")) />`

If you also load in a primary button it works fine from using the style output:

`<BFUPrimaryButton Text="Primary" OnClick=@(() => OnClickHandler("Default Primary")) />`

EDIT: Just wanted to add this also impacts non-primary Compound Buttons.

I have added the following in App.razor to work around this issue:

<BFUStylePreloader Component=@(new BFUPrimaryButton()) />

**Comment by limefrogyank** [comment]
I see... it depends on the style from the BFUPrimaryButton but if none are loaded, it won't be there.  I think what you did is the correct workaround.  I'll put it into the actual component for BFUCompoundButton instead.  Future updates shouldn't affect how you handled it.

Thanks for the report and fix!

**Comment by limefrogyank** [comment]
This commit has the fix.
https://github.com/BlazorFluentUI/BlazorFluentUI/commit/cb0d02f460cff2fd42a0a5b7bb8f8f60fb78927f
