### ISSUE TITLE
Items and Lists Documentation

### ISSUE THREAD

**Issue by srozz** [BlazorFluentUI/BlazorFluentUI#174]
Hi Guys, 

I Like what i see and would love to implement these UI components, however having a difficult time in following the documentation to implement the details list and that sort of thing. it seems that in the webpage, all the 'Items and Lists' section do not contain a code drop down which would be quite handy for myself and probably others who are struggling to implement a grid feature. cheers guys!

**Comment by NPadrutt** [comment]
Yeah that is true. For lists it is a bit tricky (at least when I tried it). 
Till that is done, you can checkout the source code of the demo directly here:

https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/Demo/BlazorFluentUI.Demo.Shared/Pages/DetailsListPageBasic.razor

Or for a more advanced example with the DynamicData Library here: 

https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/Demo/BlazorFluentUI.Demo.Shared/Pages/DetailsListPage.razor

**Comment by limefrogyank** [comment]
We're tracking that here:  https://github.com/BlazorFluentUI/BlazorFluentUI/issues/138
