### ISSUE TITLE
IconName - Some icons not showing

### ISSUE THREAD

**Issue by RicardoValero95** [BlazorFluentUI/BlazorFluentUI#182]
Hi! I've been trying to display various icons, for example: Edit, EditSolid12, EditMirrored, EditNote, etc. 
So far I've been able to display EditNote, but no success for the other ones. 

I've already checked the css file and the icons are there and are named just as I typed them 😞.
(https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css)

Here's the sample showing the EditNote icon 
`    <BFUCommandBarButton IconName="EditNote"
                         Text="Modificar"
                         OnClick="() => {  }" />`
![Annotation 2020-06-29 133156](https://user-images.githubusercontent.com/55701657/86043879-eb682180-ba0e-11ea-8601-af8c32999e3e.png)

Here's the sample not showing the icon. 
`    <BFUCommandBarButton IconName="Edit"
                         Text="Modificar"
                         OnClick="() => {  }" />`
![Annotation 2020-06-29 133410](https://user-images.githubusercontent.com/55701657/86043883-ee631200-ba0e-11ea-80cc-490ac20ebc4e.png)

I might be doing something wrong... or is there a workaround? 
Thanks in advance!

**Comment by limefrogyank** [comment]
Thanks to your investigation, I finally found the reason why some of the fonts were "missing" from the default Fluent CSS package.  We never set the dir attribute on HTML.  Apparently, that attribute is needed for some of the fonts to display!

I'll add a fix, but for now, the only workaround I can give you is to install those fonts manually.  You'll have to use the tool here: 
https://uifabricicons.azurewebsites.net/
and create your own font package and add it to your HTML.  

Once we create some new Nuget packages, it should work without any workarounds.  Thanks!

**Comment by limefrogyank** [comment]
Fixed with https://github.com/BlazorFluentUI/BlazorFluentUI/commit/933a229a385aa472c23897c670f52666aa3d9104

**Comment by limefrogyank** [comment]
Oh, the easier workaround is to add your own dir="ltr" to the HTML tag.
