### ISSUE TITLE
Issues with Detail List Selection Mode

### ISSUE THREAD

**Issue by ChristopherHaws** [BlazorFluentUI/BlazorFluentUI#184]
When `SelectionMode.Single` is selected, you can still select all the items in the list using the checkbox in the header.
```razor
<BFUDetailsList ItemsSource="forecasts"
                Columns="columns"
                LayoutMode="DetailsListLayoutMode.Justified"
                SelectionMode="SelectionMode.Single">
</BFUDetailsList>
```

![image](https://user-images.githubusercontent.com/5934505/86505074-51d5a280-bd75-11ea-934e-dc525a5e3fa8.png)

When `SelectionMode.None` is selected, you can still see the checkbox in the header and you can still select all the items:
```razor
<BFUDetailsList ItemsSource="forecasts"
                Columns="columns"
                LayoutMode="DetailsListLayoutMode.Justified"
                SelectionMode="SelectionMode.None">
</BFUDetailsList>
```
![image](https://user-images.githubusercontent.com/5934505/86505098-9e20e280-bd75-11ea-8865-d9f79e2f757e.png)

**Comment by limefrogyank** [comment]
Fixed with https://github.com/BlazorFluentUI/BlazorFluentUI/commit/f51d3ff28314f1e665f43d459a0aa9e0d6d5847b

Although I didn't test what happens with grouped lists.  There is definitely some logic that is not complete that defines when a select all is allowed with grouped lists.

**Comment by ChristopherHaws** [comment]
Not sure if I should open a new issue but I also noticed that in every selection mode, if you Ctrl+Click on the items it causes a huge delay and it looks like it is triggering out of memory exceptions.

**Comment by limefrogyank** [comment]
We can reopen this one.  I don't remember implementing Ctrl-click... but it does act like you described.  I'll check it out!  Thanks.

**Comment by limefrogyank** [comment]
This one has me dumbfounded.  I'm still looking.

**Comment by ChristopherHaws** [comment]
Perhaps its a bug in Blazor itself? It seems like something recursive is blowing up the stack till it runs out of memory.

**Comment by limefrogyank** [comment]
It doesn't show this behavior in a plain List.  But it does show it in DetailsList whether I use the complicated DynamicData library for the backing list or if I use the basic backing list.  So it's not DynamicData's fault.  I checked SelectionZone (internal to DetailsList) because it uses a Subject (Reactive library) to signal an IObservable, but my implementation of List in the demo also uses SelectionZone externally the same way.  

The only time I check for metaKey is in the contextual menu dropdown attached to buttons.  Yeah, maybe it's Blazor, but I would have expected to see it in more places.  Could be a Chromium bug....

**Comment by limefrogyank** [comment]
I may be on to something... Firefox has a slight delay when Ctrl-clicking, but not as bad as Chromium gets.

**Comment by limefrogyank** [comment]
Found the problem.  There's an unused event that is watching `keydown` on the ContentWrapper of the DetailsList.  It doesn't do anything (yet).

However, by holding down Ctrl (no reaction) and then clicking on the content area, suddenly the Ctrl key sends a stream of keydown events.  Either I can remove the keydown event as it isn't doing any logic yet, or find a way to stop the auto-repeat of the ctrl key after mouse clicking.  For now, I'll just remove the event and leave a note for when I actually want to use that event.

**Comment by limefrogyank** [comment]
Guess I was wrong... meta keys like Ctrl and Alt do register as repeatable keys when you hold them down even without the clicks.  This is pretty bad for Blazor.  
https://codepen.io/limefrogyank/pen/oNbdojE

Anyways, removing the handlers fixes things.

**Comment by limefrogyank** [comment]
Fixed with https://github.com/BlazorFluentUI/BlazorFluentUI/commit/169f939320f9ae5d71823be1b46141cf39bad015

**Comment by ChristopherHaws** [comment]
Oh wow, it really spams the browser when you hold both down. I wonder if that is intentional or if its a browser bug. Thanks for fixing this so quickly!

**Comment by ChristopherHaws** [comment]
I wonder if this would be a good candidate for overriding ShouldRender and keeping track of the state manually. It seems like blazor might be rerendering the component when it doesnt need to.

**Comment by limefrogyank** [comment]
There's a 'repeat' property on the javascript event that says whether it is being held down.  I might have to avoid blazor's onkeydown event handler and just use javascript events for keypresses.  Even if we don't render, server-side blazor is spamming the websocket with interop messages about this, too.

**Comment by limefrogyank** [comment]
I think you're also right about the ShouldRender part.  DetailsList actually controls rendering that way.  I have a simple `shouldRender` boolean that is normally set to true that I can toggle when I know an event doesn't need to make the entire component re-render.  I could just set to false that whenever I re-enable the event handlers.  <--- Notes to myself for the future.

**Comment by ChristopherHaws** [comment]
I'm not 100% sure this is the same but it looks like there is an issue for something very similar in the aspnetcore repo: https://github.com/dotnet/aspnetcore/issues/10558

Looks like they are looking into ways to allow for debouncing (throttling) of events in 5.0

**Comment by limefrogyank** [comment]
I'm glad they're looking at throttling mechanisms.  I ran into similar issues when I was trying to make a virtualized list with onscroll without using javascript.  It would overload the server-side socket connection and cause a crash.  I think we're stuck with javascript for really advanced scenarios until then.
