### ISSUE TITLE
Issue displaying L and XL Panel at 1503 width and above

### ISSUE THREAD

**Issue by Matthewsre** [BlazorFluentUI/BlazorFluentUI#185]
When the page/media width is 1503 or higher the width of the panel drops down to 940 from auto which shrinks the panel and detaches it from the right side. This happens for both Large and ExtraLarge PanelType.

CSS when page width below 1503:
![image](https://user-images.githubusercontent.com/2955659/86508788-a853d880-bd97-11ea-80aa-0e780ee4881f.png)

CSS when page width at 1503 or above:
![image](https://user-images.githubusercontent.com/2955659/86508811-d507f000-bd97-11ea-90c5-4f2c3fa1a568.png)

**Comment by limefrogyank** [comment]
Yeah, I can confirm.  I'll make a fix for this soon.

**Comment by limefrogyank** [comment]
Fixed with https://github.com/BlazorFluentUI/BlazorFluentUI/commit/1f83463678595bde9a66bb0cb1e50206d5591ac1

**Comment by limefrogyank** [comment]
I'll make some new Nuget packages later today
