### ISSUE TITLE
ResponsiveLayout documentation or demo

### ISSUE THREAD

**Issue by peteryulius** [BlazorFluentUI/BlazorFluentUI#187]
There are responsive layout component documentations or sample demo?

**Comment by limefrogyank** [comment]
Best we have is its usage in the demo:
https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/Demo/BlazorFluentUI.Demo.Shared/Shared/MainLayout.razor

**Comment by limefrogyank** [comment]
And of course the demo itself:  https://www.blazorfluentui.net/

if you resize the window, the navigation layout will change.

**Comment by peteryulius** [comment]
Awesome. Thanks for your efforts, great work.
