### ISSUE TITLE
DotNetObjectReferences must be disposed

### ISSUE THREAD

**Issue by limefrogyank** [BlazorFluentUI/BlazorFluentUI#188]
I'm not sure when this showed up on the Blazor docs, but it seems you have to dispose of `DotNetObjectReference` either from the .NET side or javascript side.  There are a few components that do JSInterop that need this to be implemented in the Dispose method.

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1#instance-method-call

This might help with odd errors with page refreshes.  (Only an issue when debugging... normally it gets ignored.)  Regardless there are some memory leaks.

**Comment by limefrogyank** [comment]
FYI, if javascript is being called, then we need to use IAsyncDisposable, not IDisposable.  This is new in NET5.

**Comment by vnbaaij** [comment]
`DisposeAsync()` is added to all classes using JS interop in V5.2.2
