### ISSUE TITLE
[Feature Request] Support for Blazor @bind @bind-Value on input elements

### ISSUE THREAD

**Issue by joschemd** [BlazorFluentUI/BlazorFluentUI#19]
This is a quality of life request to add in support for Blazor binding semantics.
Current:
`
<TextField Value="@Model.Property" OnChange="@HandleChange" />
`
Preferred:
`
<TextVield @bind-Value="@Model.Property"/>
`

**Comment by limefrogyank** [comment]
So basically, just change all of the event names to `{propertyName}Changed`...

That makes sense.  I was initially trying to keep some sense of unity with the react version, but I guess that doesn't matter.

**Comment by limefrogyank** [comment]
I'll be trying this out with the `Toggle` control I'm currently making.  Since the property is `Checked`, the event will be `CheckedChanged` and hopefully the two-way binding will just work.

**Comment by joschemd** [comment]
I've done some work to get it up and running, once I have an extra free moment, I'll send you my  implementation for you to peruse. It's working with input fields and a few other items but would need to do more refactoring to get everything setup.. it was actually not too difficult, but could potentially break a pattern.

**Comment by limefrogyank** [comment]
So it seemed to work fine with my `Toggle` implementation 

```
<Toggle @bind-Checked=@BoundChecked OnText="On!" OffText="Off!" Label="This is a toggle using binding." />
```

**Comment by joschemd** [comment]
I'll send you my merged updates here this weekend. Stay tuned.

**Comment by limefrogyank** [comment]
I added a default ValueChanged to `TextField` and I believe the other components are setup similarly.  
https://github.com/BlazorFluentUI/BlazorFluentUI/commit/511676093038a22e2caf04d7c3ceac7c056f2778
