### ISSUE TITLE
utilize a build system

### ISSUE THREAD

**Issue by sebfischer83** [BlazorFluentUI/BlazorFluentUI#197]
I think it would be a nice addition to use something like NUKE for building the libraries and generating all needed javascript files.

**Comment by limefrogyank** [comment]
I'm not opposed to automating things, but I don't know anything about nuke.  Feel free to set it up in a pull request.  If it looks easy to use (and modify), we'll probably use it.

**Comment by NPadrutt** [comment]
I would vote for having something in github actuons since already a partnis there. Unless you can integrate nuke there.

**Comment by matkoch** [comment]
nuke generates github action definitions

**Comment by sebfischer83** [comment]
I would like to make a proposal but the next weeks I don`t have any time

**Comment by vnbaaij** [comment]
Closing this as we have a build system in place now
