### ISSUE TITLE
Query string in the URI messes with BlazorFluentUI CSS styling 

### ISSUE THREAD

**Issue by devanshidiaries** [BlazorFluentUI/BlazorFluentUI#202]
#### This how the UI CSS styling displays with query string.
![image](https://user-images.githubusercontent.com/42736080/89745944-b3bbb300-da6b-11ea-85d9-3a3db7e338a8.png)

#### Once I use the browser(any browser - Chrome/Edge/Safari) buttons for going back, forward or refreshing the page, the UI CSS styling gets messed up as shown below.
![image](https://user-images.githubusercontent.com/42736080/89745797-f630c000-da6a-11ea-928e-efd79785b11b.png)

#### Any suggestions to fix this?

**Comment by limefrogyank** [comment]
Wow, that's a nice looking layout.  👍

Are those layout changes from `div` tags with flex styling from a stylesheet?  Or are they being styled directly using a style attribute?  Or are you using `BFUStack`?  I haven't really seen this before and I'm just trying to get a clue to why this might happen.  I'd check to see what styles are or are not being applied on the F12 debug page...

I think we only use `BFUStack` in the demo... and some other custom components for the nav sidebar layout.  Going back on the demo doesn't do that.  As far as I know, the back button in the browser is intercepted by the Blazor `Router` which checks to see if the URL base is the same.  If so, it prevents the standard nav and instead renders the correct razor page.  So, everything **should** be rendered the same as if you navigated forwards.  

Unless the new page somehow has a different stylesheet?  You're not supposed to load css stylesheets except for on the root page... but I don't know if you're doing that.

**Comment by limefrogyank** [comment]
oh, refreshing does it, too???  So, I have seen fonts break before when refreshing... but not all the rest of the styling.  Let me think about it.

**Comment by limefrogyank** [comment]
Stupid question but... are there any console errors showing up?

**Comment by devanshidiaries** [comment]
The style references exist in the _Host.cshtml file.

    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <base href="~/" />
    <link href="css/site.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css" />
    <link rel="stylesheet" href="css/fabric-icons-inline.css" />
    <link rel="stylesheet" href="css/ProgressControl.min.css" />
    <script src="_content/BlazorFabric.BaseComponent/baseComponent.js"></script>
    <link rel="stylesheet" href="_content/BlazorFabric.BaseComponent/styles.css" />
    <script src="_content/MatBlazor/dist/matBlazor.js"></script>
    <link href="_content/MatBlazor/dist/matBlazor.css" rel="stylesheet" />
    <link rel="stylesheet" href="_content/BlazorFabric.Button/button.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Calendar/calendar.css" />
    <script src="_content/BlazorFabric.Callout/callout.js"></script>
    <link rel="stylesheet" href="_content/BlazorFabric.Callout/callout.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Checkbox/checkbox.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.CommandBar/commandBar.css" />
    <script src="_content/BlazorFabric.ContextualMenu/contextualMenu.js"></script>
    <link rel="stylesheet" href="_content/BlazorFabric.ContextualMenu/contextualMenu.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.DatePicker/datePicker.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Dialog/dialog.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Dropdown/dropdown.css" />
    <script src="_content/BlazorFabric.FocusTrapZone/focusTrapZone.js"></script>
    <script src="_content/BlazorFabric.FocusZone/focusZone.js"></script>
    <link rel="stylesheet" href="_content/BlazorFabric.Icon/icon.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Image/image.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Label/label.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Layer/layer.css" />
    <script src="_content/BlazorFabric.List/fabricList.js"></script>
    <link rel="stylesheet" href="_content/BlazorFabric.List/list.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Link/link.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.MessageBar/messageBar.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Modal/modal.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Nav/nav.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.OverflowSet/overflowSet.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Overlay/overlay.css" />
    <script src="_content/BlazorFabric.Panel/panel.js"></script>
    <link rel="stylesheet" href="_content/BlazorFabric.Panel/panel.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Persona/persona.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Pivot/pivot.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.ProgressIndicator/progressIndicator.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Rating/rating.css" />
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="_content/BlazorFabric.RichTextEditor/richTextEditor.js"></script>
    <link rel="stylesheet" href="_content/BlazorFabric.RichTextEditor/richTextEditor.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Spinner/spinner.css" />
    <script src="_content/BlazorFabric.TextField/fabricTextField.js"></script>
    <link rel="stylesheet" href="_content/BlazorFabric.TextField/textfield.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Toggle/toggle.css" />
    <link rel="stylesheet" href="_content/BlazorFabric.Tooltip/tooltip.css" />

The Blazor packages are:

    <PackageReference Include="Blazored.TextEditor" Version="1.0.3" />
    <PackageReference Include="BlazorFabric.Button" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Checkbox" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Dropdown" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Icon" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Label" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.DatePicker" Version="2.2.0" />    
    <PackageReference Include="BlazorFabric.List" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Nav" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Panel" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Persona" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.ResponsiveLayout" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.RichTextEditor" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Spinner" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Stack" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Text" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Pivot" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.TextField" Version="2.2.0" />
    <PackageReference Include="BlazorFabric.Toggle" Version="2.2.0" />
    <PackageReference Include="MatBlazor" Version="2.4.3" />

We are using these older BlazorFabric package versions because they were the latest when we started creating and now the newer one is breaking the code at multiple points.

**Comment by devanshidiaries** [comment]
I was able to **fix** the css by setting a fixed base url in my _host.cshtml here 

    <link rel="stylesheet" href="https://crlf.azurewebsites.net/css/bootstrap/bootstrap.min.css" />
    <base href="~/" />

**I replaced the `base href link` with my fixed url value.**

Is this the right way?

**Comment by limefrogyank** [comment]
Ah, that makes sense!  When you navigate to a URL with anything in the path (i.e. something.com/someFolder/somePage), if the css path is "_content/BlazorFabric.ContextualMenu/contextualMenu.css", it looks for the css in "something.com/someFolder/_content/BlazorFabric.ContextualMenu/contextualMenu.css".  

It seems we should have used a leading slash in the css path to say to always look in the root folder.

Looks like your workaround is ok, too.  You can always try putting a leading slash in the css path names if you need to change your base path.

Sorry, this is such fundamental html stuff and I failed to see it 🤦‍♂️
