### ISSUE TITLE
BFUCompoundButton not using AriaLabel="" and ClassName="" when set

### ISSUE THREAD

**Issue by Matthewsre** [BlazorFluentUI/BlazorFluentUI#203]
I was looking to add a ClassName and AriaLabel to the BFUCompound button, but when setting these values it has no impact on the html of the rendered button. Looks like this might not be working correctly with the BFUComponentBase?

**Comment by limefrogyank** [comment]
I think `ClassName` should be working on `BFUCompoundButton`, but it looks as if it's applied to the internal `<button>` element (or `<a>` element), not the root div.  
 https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/src/BlazorFluentUI.BFUButton/BFUButtonBase.cs#L625

The elements that are wrapping the internal button are mostly dummy elements that are in place for when we finally implement `BFUKeyTip`.  (A component that overlays keyboard shortcuts when you hold Alt key)

As for `AriaLabel`, yeah, I don't see it.  Looks like we have `aria-description` and `aria-hidden` implemented (aria-hidden is internal).  We should probably get this one working.
