### ISSUE TITLE
BFUSlider not in NuGet package

### ISSUE THREAD

**Issue by LingRepo** [BlazorFluentUI/BlazorFluentUI#205]
I can not use it Blazor pages

**Comment by limefrogyank** [comment]
Oh, I still haven't published a new NuGet package since that was made.  I'll do it soon.

**Comment by LingRepo** [comment]
Thanks.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Lee McPherson <notifications@github.com>
发送时间: Friday, September 4, 2020 6:41:55 AM
收件人: BlazorFluentUI/BlazorFluentUI <BlazorFluentUI@noreply.github.com>
抄送: Ling <lingjing0921@live.com>; Author <author@noreply.github.com>
主题: Re: [BlazorFluentUI/BlazorFluentUI] BFUSlider not in NuGet package (#205)


Oh, I still haven't published a new NuGet package since that was made. I'll do it soon.

―

**Comment by limefrogyank** [comment]
Sorry for the delay again.  The latest version is on NuGet and should have BFUSlider now.
