### ISSUE TITLE
Column width in BFUDetailsList being set to NaN

### ISSUE THREAD

**Issue by mparkms** [BlazorFluentUI/BlazorFluentUI#213]
When using BFUDetailsList, if I set the LayoutMode to FixedColumns, all of the column widths are being set to NaN, which breaks the table:
![image](https://user-images.githubusercontent.com/9259787/95636699-a5c2e800-0a44-11eb-8f5f-81f948f1a5e7.png)

Inspecting the HTML, I can see the width is being set to "NaNpx":
![image](https://user-images.githubusercontent.com/9259787/95636827-fe928080-0a44-11eb-87a6-1ac4513e5a87.png)

This also sometimes happens when the LayoutMode is set to Justified, and you try to resize the columns to be very small. In that case only one of the columns' widths gets set to NaN, but it still breaks the table.

**Comment by limefrogyank** [comment]
I can't replicate the `NaN`.  When I set my DetailsList to FixedColumns and remove the MaxWidth or MinWidth from the columns info, it defaults to 300px widths.  Is there some combination of parameters that does this?

I can't replicate the justified NaN either.  There is definitely a problem with the column widths though.  The resizer doesn't respect the min or max width settings... and if I drag it past where it would be zero width, I can make it have negative width in the style.

**Comment by vnbaaij** [comment]
This works as expected now. See the sample at https://www.blazorfluentui.net/detailsListAutoPage
