### ISSUE TITLE
BFUTextField @onchange throwing InvalidCastException

### ISSUE THREAD

**Issue by Cobra86** [BlazorFluentUI/BlazorFluentUI#214]
Blazor page:
```
<BFUTextField @onchange="OnChange"></BFUTextField>

@code {

    public void OnChange(ChangeEventArgs e)
    {
        var test = e.Value;
    }
}
```
Error:
```
InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Components.EventCallback`1[Microsoft.AspNetCore.Components.ChangeEventArgs]' 
to type 'Microsoft.AspNetCore.Components.EventCallback`1[System.String]'.
```

**Comment by limefrogyank** [comment]
The OnChange callback in our library only returns a `string`, not `ChangeEventArgs`.  I don't think that existed in Blazor when we started...  feel free to create a PR with that change if you think it would be useful.

**Comment by Cobra86** [comment]
I've created a pull request. I hope my code is matching the project code standards. :)

**Comment by vnbaaij** [comment]
Closed. See #215 for details why this has not been merged
