### ISSUE TITLE
Custom column rendering DetailList

### ISSUE THREAD

**Issue by bobonic** [BlazorFluentUI/BlazorFluentUI#216]
How can we render customize column display? I want to display title when hovering into columns. In Fabric we can do it on onRenderItemColumn

![image](https://user-images.githubusercontent.com/2681829/95708151-190b6a80-0c8e-11eb-8cf8-d68e2ff4e87d.png)

**Comment by limefrogyank** [comment]
You should be able to use `ColumnItemTemplate` inside the `BFUDetailsRowColumn` column definition.  I'm not sure if I've really tested it though so let me know.

**Comment by bobonic** [comment]
How to use `ColumnItemTemplate`?

**Comment by limefrogyank** [comment]
In razor direct:
```
<ColumnItemTemplate>
    <div>something</div>
</ColumnItemTemplate>
```

In Razor/C#:
```
ColumnItemTemplate = item => builder => {
   <div>@item.name</div>
};
```

In full C#:
```
ColumnItemTemplate = item => builder =>{
   builder.OpenElement(0, "div");
   //etc
   builder.CloseElement();
};
```

**Comment by limefrogyank** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/templated-components?view=aspnetcore-3.1

**Comment by bobonic** [comment]
` Columns.Add(new BFUDetailsRowColumn<AgentModel>("CreatedDate", x => x.CreatedDate) { Index = 0, OnColumnClick = this.OnColumnClick, ColumnItemTemplate =  });`

do i need to create a method and set it to `ColumnItemTemplate `? or i will
`<BFUDetailsRowFields>

</BFUDetailsRowFields>`

inside the `<BFUDetailsList>`

**Comment by bobonic** [comment]
heres my fragment, how i can pass the value of the column

`RenderFragment<IComparable> CreatedDateColumn = (item) =>@<div title="@item">@item</div>;`

1ColumnItemTemplate = CreatedDateColumn`
