### ISSUE TITLE
Can't set MinDate dynamically

### ISSUE THREAD

**Issue by NPadrutt** [BlazorFluentUI/BlazorFluentUI#217]
I try to set the min date dynamically to a property in my code. 

My DatePicker:
```
            <BFUDatePicker Label=@Localizer["DateLabel"]
                           FirstDayOfWeek="DayOfWeek.Monday"
                           IsRequired
                           MinDate="@NextValidDate"
                           FormatDate="(date) => date.ToShortDateString()"
                           Disabled="SelectedTimeTracking.IsBilled"
                           @bind-Value="SelectedTimeTracking.Date" />
```

And the property:

        private DateTime nextValidDate;
        protected DateTime NextValidDate
        {
            get => nextValidDate;
            set
            {
                nextValidDate = value;
                StateHasChanged();
            }
        }

I set the NextValidDate in the OnInitializedAsync. I tried the OnParameterSet as well but it doesn't make any difference.
Also I tried to use the "@bind-" Notation, but I guess for that we are missing an "Changed" Event Handler.

Any idea how to achieve this?

**Comment by limefrogyank** [comment]
You're saying if you change NextValidDate yourself, the minimum selectable date range on the Calendar that pops up does not change?  I was looking and I don't see a reason why that wouldn't happen.  I'll give it a test in a little bit.

**Comment by NPadrutt** [comment]
Shoot, soory false alarm.. it works as expected. I just got not the expected date back from the server because the data is different on this computer as I had in mind..
