### ISSUE TITLE
RichTextEditor - Insert image is not working.

### ISSUE THREAD

**Issue by Cobra86** [BlazorFluentUI/BlazorFluentUI#219]
Insert image isnt working in the richtext editor. 

![image](https://user-images.githubusercontent.com/7024154/96779086-3fdf4480-13e4-11eb-850f-d9e8e703e028.png)

**Comment by limefrogyank** [comment]
I just tried it in the server side demo and it works for me... 

Did it crash after you tried to insert an image?  If so, what did you use for the parameters?

**Comment by Cobra86** [comment]
Yes. i used this image https://www.w3.org/People/mimasa/test/imgformat/img/w3c_home.jpg
I'm using chrome and this the console log 
![image](https://user-images.githubusercontent.com/7024154/96798362-a5d5c700-13f8-11eb-8fee-ed11163ec97d.png)

**Comment by limefrogyank** [comment]
Ah, I see.  If you never place your cursor in the RichTextEditor box but try to add an image, it will throw an exception.  

If you click on the box first to add a cursor, then it works.  I can probably fix this...

**Comment by limefrogyank** [comment]
I'm not sure if we're going to release another version before v4 (net5) comes out.  In the meantime, an easy workaround is to stop using the bundled richTextEditor.js and instead create your own from this file:
https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/src/BlazorFluentUI.BFURichTextEditor/wwwroot/richTextEditor.js#L189

But change the last line to:
```
 quill.insertEmbed(this.lastSelection ? this.lastSelection.index : 0, "image", { src: imageUrl, alt: imageAlt, width: imageWidth !== null ? imageWidth : undefined, height: imageHeight !== null ? imageHeight : undefined });
```
When the input box has not had any interaction, `this.lastSelection` is null and so checking the `index` fails.  I just added a null check that defaults to zero for the index if it's never been clicked.

**Comment by limefrogyank** [comment]
Fixed with https://github.com/BlazorFluentUI/BlazorFluentUI/commit/498a2c28746874f250d83e4ffc0d9ded0cb3e8a8 in net5 branch
