### ISSUE TITLE
Could not find 'BlazorFluentUiBaseComponent' in 'window'

### ISSUE THREAD

**Issue by mariohik** [BlazorFluentUI/BlazorFluentUI#220]
I'm trying to use Dropdown in a Blazor WebAssembly application with Login.
When the user is not logged in, the exception "Could not find 'BlazorFluentUiBaseComponent' in 'window'" appears, but when the user is logged in, it is not.
Was it a configuration error?

**EDIT**
This exception does not occur on my notebook (neither in DEBUG nor RELEASE). It only happens when I publish the application on the IIS server.

**Comment by limefrogyank** [comment]
Maybe you don't have your url base set correctly on your index.html?

**Comment by limefrogyank** [comment]
Is the IIS server local, too?  Because if it's through a domain with cloudflare:

https://zimmergren.net/solved-asp-net-core-blazor-web-sites-does-not-work-with-cloudflare-html-minification/

**Comment by maacpiash** [comment]
I am having the same issue on Blazor Server app. It is an app freshly initiated via .NET CLI. I installed the NuGet package and added the necessary lines in `_Imports.razor`, `_Host.cshtml` and `Startup.cs`. Then I wrapped the whole app inside `BFUTheme` component (in `App.razor`), as instructed in the wiki. Now, this same error shows up on my terminal when I try to navigate to the app home page, which contains a `BFUTextField`.

**Comment by limefrogyank** [comment]
I'll have to try to make one from scratch, too.  Let me see if I run into the same issue...

**Comment by limefrogyank** [comment]
Just tried from a fresh install of a server app (using VS 2019 preview 1.0).  
![image](https://user-images.githubusercontent.com/7821384/101937453-b99adf80-3b96-11eb-8640-91454b81a5af.png)
Works fine!

I did find a mistake in the wiki.  When you add 
```
services.AddBlazorFluentUI();
```
it should be inside the `Configure` method, not the `Main` method.  

But everything else works.  I didn't realize that the default templates also add the css files automatically, so we really don't even need that.  

This is a javascript problem.  If javascript files can't be found, I would encourage you to clear the browser cache.  If you don't want to do that, then try an InPrivate tab to load the page (or whatever the Chrome/Firefox equivalent is).  Also, double-check there are no typos in the src link.

**Comment by maacpiash** [comment]
@limefrogyank, first of all, I would like to thank you for your time and effort to attempt to solve my issue. This problem, unfortunately, still persists.

The issue might arise from the fact that I am using **version 3.1.6**, the latest version I could find that plays well with ASP.NET Core 3.1.

After reading your comment, I initiated a fresh Blazor server project (v3.1) and added the necessary modifications. Then I started the project and opened the page in an incognito/private window. It still shows the same error.

Here is the repo, if you're interested: https://github.com/maacpiash/blazor-fluent-ui-demo

**Comment by limefrogyank** [comment]
Unfortunately, the older v3 of this library needs a bit more setup because of how we were handling styles.  I would browse the server-side demo that we had during v3... somewhere around here in this commit https://github.com/BlazorFluentUI/BlazorFluentUI/blob/113f7469c6fbbb78a2854f5c021f9508f2e3a522/Demo/BlazorFluentUI.Demo.ServerSide/Pages/_Host.cshtml#L37

Notice the `BFUGlobalRules` component.  

https://github.com/BlazorFluentUI/BlazorFluentUI/blob/113f7469c6fbbb78a2854f5c021f9508f2e3a522/Demo/BlazorFluentUI.Demo.Shared/App.razor

The `BFUStylePreloader` is not required, but you may find pages load a little faster after initial load.

**Comment by vnbaaij** [comment]
Closing this as it was happening in older (V3) version
