### ISSUE TITLE
BFUDetailsRowColumn OnRender Missing

### ISSUE THREAD

**Issue by MicahN-ISS** [BlazorFluentUI/BlazorFluentUI#221]
Greetings,

I see in the React Fluent UI that the DataList column object has an onRender to do some formatting/html for the row cell.

I am not seeing this in the BlazorFluentUI BFUDetailsList -> BFUDetailsRowColumn  column object.  

I am assuming it is not implemented or there is an alternate Row-Column renderer that I am not understanding.

Thanx

**Comment by limefrogyank** [comment]
Should be called RowTemplate instead... Or something like that. It accepts a RenderFragment so you should be able to define it via razor code.

Lee Mc

________________________________

**Comment by MicahN-ISS** [comment]
Ahhh...got it I see it now.

Thanx
