### ISSUE TITLE
Can't get BFUDetailsList RowTemplate to work

### ISSUE THREAD

**Issue by GeertvanHorrik** [BlazorFluentUI/BlazorFluentUI#223]
When I use this code, it shows the data:

```
                <BFUDetailsList ItemsSource="SearchResult"
                                IsVirtualizing="false"
                                SelectionMode="SelectionMode.None"
                                Compact="false"
                                Columns="@columns"
                                LayoutMode="DetailsListLayoutMode.Justified" />
```

When I try to replace the RowTemplate, it shows no rows (only header):

```
                <BFUDetailsList ItemsSource="SearchResult"
                                IsVirtualizing="false"
                                SelectionMode="SelectionMode.None"
                                Compact="false"
                                Columns="@columns"
                                LayoutMode="DetailsListLayoutMode.Justified">
                    <RowTemplate>
                        <p>@context.GetProperty("id").GetGuid()</p>
                    </RowTemplate>
                </BFUDetailsList>
```

I also tried adding the default BFUDetailsRow directly without results:

```
                <BFUDetailsList ItemsSource="SearchResult"
                                IsVirtualizing="false"
                                SelectionMode="SelectionMode.None"
                                Compact="false"
                                Columns="@columns"
                                LayoutMode="DetailsListLayoutMode.Justified">
                    <RowTemplate>
                        <BFUDetailsRow Item=@context
                                       Columns=@columns
                                       SelectionMode="SelectionMode.None"
                                       Compact="false"
                                       CheckboxVisibility="CheckboxVisibility.Hidden" />
                    </RowTemplate>
                </BFUDetailsList>
```

The reason I want to override is to show a tooltip (as a card) per row when the user hovers a row.

**Comment by limefrogyank** [comment]
First, `<RowTemplate>` uses a `IndexedItem<TItem>` for the context, so if you want to override the row and show and item, you need to use `@context.Item.someProperty`.  `IndexedItem<TItem>` just has Item and Index properties.

Second, if you want to show a tooltip for the whole row where it doesn't matter what cell you're hovering over, yeah, you can add a `<RowTemplate>`.  But I would recreate at the very least how `BFUDetailsList` does it internally and then just wrap it in the `Tooltip` stuff.  See the source...

Third, if you just want a tooltip on certain cells in your rows, you can instead use the `BFUDetailsRowColumn` item that goes with that column:
```
 Columns.Add(new BFUDetailsRowColumn<DataItem>("Name", x => x.DisplayName)
        {
            Index = 1,
            MaxWidth = 150,
            OnColumnClick = this.OnColumnClick,
            IsResizable = true,
            ColumnItemTemplate = item => @<div> @item.someProperty</div>
        });
```

**Comment by GeertvanHorrik** [comment]
Thanks for your reply!

I don't understand how it can be of IndexedItem, intellisense tells me otherwise:

![image](https://user-images.githubusercontent.com/1246444/98036432-5214a600-1e1a-11eb-9c62-119fff9d0e8a.png)

Will try to explicitly specify it.

**Comment by limefrogyank** [comment]
Ohh… I’ve been looking at my other branch.  Maybe I changed it since then.

Sorry about that… you’re right.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by GeertvanHorrik** [comment]
I did a full clone (of this component) and wrapped all instances of the row usage inside a tooltip and it's working fine. I'm not in a hurry, but just wanted to let you know.

**Comment by GeertvanHorrik** [comment]
btw .net 5 will be released in about 1 week, not sure whether it's worth backporting.
