### ISSUE TITLE
.NET 5 RC 2

### ISSUE THREAD

**Issue by GeertvanHorrik** [BlazorFluentUI/BlazorFluentUI#225]
Is there a way to test the latest bits (e.g. nuget packages) that allow us to test the prerelease against .NET 5 which will be released this week?

The current packages are about 1 month old and I think a lot has improved since.

Thanks!

**Comment by NPadrutt** [comment]
Hi @GeertvanHorrik 
we are currently working on a CI/CD pipeline. With that you should be able to get always the latest bits packed up as a nightly via a custom nuget feed. Also it should be easier for us to publish preview packages in general.
We should soon (like in the next couple of hours I hope) some updates on this. I'll write here once that is the case.

**Comment by limefrogyank** [comment]
Actually, RC2 should be available as a NuGet package if you select the show preview package option...

**Comment by GeertvanHorrik** [comment]
@NPadrutt  Fantastic news, looking forward to the update

@limefrogyank They are about 1 month old. I am having some troubles getting them to work (which is totally on my end, but was hoping for an update, especially since the BFUI says RC).

I tried following the examples from the net5 branch (and removed the StylePreloader), but still having issues with styling.

**Comment by limefrogyank** [comment]
Oh, right... the installation instructions will have to be different.  The link to the css file is different and we don't need the GlobalCS stuff anymore.  You'd have to look at the demo source code to see what changes to make until I get the instructions fixed.

**Comment by limefrogyank** [comment]
https://github.com/BlazorFluentUI/BlazorFluentUI/wiki/How-To-Use:-ClientSide-Blazor

It's been updated to show how to setup everything.  It's not that different... a few things removed and a few small changes.

**Comment by GeertvanHorrik** [comment]
Thank you very much! Will try to change.

**Comment by GeertvanHorrik** [comment]
Fantastic, styles are working again, it was the project specific css file that I missed, thanks!

**Comment by NPadrutt** [comment]
@GeertvanHorrik as promised before, there is a new public feed for nuget's which are built after each commit. You can find it under this link: https://dev.azure.com/blazor-fluentui/Blazor%20FluentUI/_packaging?_a=feed&feed=DevChannel. When you click on "Connect To Feed" you can select your platform and get a nice tutorial how to add it.

Also @limefrogyank published version 4.0.0 to nuget.

**Comment by GeertvanHorrik** [comment]
Fantastic work, thanks. The ci builds are a huge step forward, well done! Thanks for all the effort.
