### ISSUE TITLE
Upgrade to 4.0 Issues and Questions

### ISSUE THREAD

**Issue by MicahN-ISS** [BlazorFluentUI/BlazorFluentUI#229]
I set up a new branch from master on my app that was using the previous version of this framework then to upgrade to 4.0.  Previous version worked fine.  I upgraded, your "breaking changes" notes were quite small, thus felt like easy upgrade.

Note:  The v4 I can see is faster to load..sweet!

Here are my issues:
Note:  I have tried various things because I am a good programmer and I see the source, but I just get errors, and just do not understand the issue from working in v 3 and fail in v 4.
```
<div data-is-scrollable="true" style="height:400px;overflow-y:auto;">
        <BFUDetailsList ItemsSource="UserRoleListItems" TItem="RoleBasedAccessModel"
                        IsHeaderVisible="true"
                        Columns="Columns"
                        GetKey=@(x=>x.Id)
                        LayoutMode="DetailsListLayoutMode.Justified"
                        SelectionMode=@SelectionMode.Single
                        Selection="selectedItem" 
                        SelectionChanged="SetSelectedUser" /> <-- this worked before now gone (SelectionChanged)
    </div>
```
BFUDetailsList SelectionChange is gone <- how do I set my selected item in the list event.
I tried all kinds of crazy events, funcs, lambdas I just could not figure this out.  But why change?

```

I changed to BFUDetailsListAuto which does have the SelectionChanged and I get error
<div data-is-scrollable="true" style="height:400px;overflow-y:auto;">
        <BFUDetailsListAuto  ItemsSource="UserRoleListItems" TItem="RoleBasedAccessModel"
                        IsHeaderVisible="true"
                        Columns="Columns"
                        GetKey=@(x=>x.Id)
                        LayoutMode="DetailsListLayoutMode.Justified"
                        SelectionMode=@SelectionMode.Single
                        Selection="selectedItem"
                        SelectionChanged="SetSelectedUser"/>
    </div>
```

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Value cannot be null. (Parameter 'second')
System.ArgumentNullException: Value cannot be null. (Parameter 'second')
   at System.Reactive.Linq.Observable.Merge[PropertyChangedEventArgs](IObservable`1 first, IObservable`1 second) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable.Multiple.cs:line 572
   at BlazorFluentUI.BFUDetailsListAuto`1.<>c[[UnifiedIntakeTool.Shared.Models.RoleBasedAccessModel, UnifiedIntakeTool.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<CreateSourceCache>b__134_17(IObservable`1 x, BFUDetailsRowColumn`1 y)
   at System.Linq.Enumerable.Aggregate[BFUDetailsRowColumn`1,IObservable`1](IEnumerable`1 source, IObservable`1 seed, Func`3 func)
   at BlazorFluentUI.BFUDetailsListAuto`1[[UnifiedIntakeTool.Shared.Models.RoleBasedAccessModel, UnifiedIntakeTool.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<CreateSourceCache>b__134_4(PropertyChangedEventArgs prop)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._[[System.ComponentModel.PropertyChangedEventArgs, System.ObjectModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.ComponentModel.PropertyChangedEventArgs, System.ObjectModel, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].OnNext(PropertyChangedEventArgs value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 869

then in the same page, I get a new error with the checkbox: <- working in v 3
![image](https://user-images.githubusercontent.com/9000210/98775096-40467c00-23a1-11eb-9f00-887790876fb8.png)

This is my code from v 3 working fine within a EditForm to manage user RBAC in an admin page. 
```
<EditForm id="addUserForm" Model="@userData" OnSubmit="@AdduserDataAsync">
        <div>
            <BFUTextField Label="User Fullname:"
                          Disabled="@(userData.Id != Guid.Empty)"
                          Required="true"
                          @bind-Value="@userData.UserFullName" @bind-Value:event="OnInput" />
        </div>
        <div>
            <BFUTextField Label="User Email:"
                          Disabled="@(userData.Id != Guid.Empty)"
                          Required="true"
                          @bind-Value="@userData.UserEmail" @bind-Value:event="OnInput" />
        </div>
        <div className="ow-role-inputs">
            <BFUCheckbox Label="Owner"
                         Checked="@userData.Roles.Where(x => x.RoleName.Equals("Owner")).Any()"
                         CheckedChanged="@(eventArgs => { RoleChange("Owner", eventArgs); })" />

            <BFUCheckbox Label="Administrator"
                         Checked="@userData.Roles.Where(x => x.RoleName.Equals("Administrator")).Any()"
                         CheckedChanged="@(eventArgs => { RoleChange("Administrator", eventArgs); })" />

            <BFUCheckbox Label="User"
                         Checked="@userData.Roles.Where(x => x.RoleName.Equals("User")).Any()"
                         CheckedChanged="@(eventArgs => { RoleChange("User", eventArgs); })" />

            <BFUCheckbox Label="ReadOnly"
                         Checked="@userData.Roles.Where(x => x.RoleName.Equals("ReadOnly")).Any()"
                         CheckedChanged="@(eventArgs => { RoleChange("ReadOnly", eventArgs); })" />
        </div>
    </EditForm>
```

your framework code:
 ```
protected override Task OnParametersSetAsync()
        {
            if (CascadedEditContext != null)
            {
                if (CheckedExpression == null)
                {
                    **throw new InvalidOperationException($"{GetType()} requires a value for the 'CheckedExpression' " +
                        $"parameter. Normally this is provided automatically when using 'bind-Checked'.");**
                }
                FieldIdentifier = FieldIdentifier.Create<bool>(CheckedExpression);

                CascadedEditContext?.NotifyFieldChanged(FieldIdentifier);

                CascadedEditContext.OnValidationStateChanged += CascadedEditContext_OnValidationStateChanged;
            }
```
I am not good at looking and GIT diffs, but what changed here?  how do I fix this?  **I moved the checkbox out of the EditForm elements to fix issue.** <- why?

Finally,
This one is really stumping me... v3 DataList render fine v 4, I get some extra "}" that throws my styling off.   Same code as v3, but v4 get extra "}" in my list  <- again, possibly something on my end, but very strange
![image](https://user-images.githubusercontent.com/9000210/98775946-ed6dc400-23a2-11eb-829a-a6c223ff87f8.png)

So, I am questioning why the v3 working fine, I just upgrade Nuget to v4 and my app fails with DataList issues and Checkbox as a child of an EditForm issue, and some rando '}' in my DataLists. 

Finally, I would like to help out on this repo once I get caught up and understand a bit more.

Cheers!

**Comment by GeertvanHorrik** [comment]
I am seeing the } as well.

**Comment by NPadrutt** [comment]
@MicahN-ISS When I understand your issue correctly you have mixed in like 3 issues in one which makes it a bit difficult. Especially since there is no separation between the topics. So making separate issues would definitely help for a next time :)

For the bracket at the end of the row I created a PR (#231 ). (FYI @GeertvanHorrik )

For the selection I think @limefrogyank  released a version 4.0.1 which should invoke the selection again.
I also submitted PR #232 which would readd the Invoke / click event. In that case a click on the item itself would execute the invoke and a click on the bubble at the beginning of the line the selection. AFAIK that is the behaviour in 3.1.6 as well as in the react version of FluentUI.

**Comment by limefrogyank** [comment]
Apologies, but Selection was such a big rewrite (and over a few months) that I had forgotten all of the changes.  First, `SelectionChanged` on the `DetailsListAuto` was a mistake left in.  It doesn't do anything.

If you want to change which item is selected programmatically, you should use the `Selection<TItem>` object that you attach to the `DetailsList`:

`void SetIndexSelected(int index, bool isSelected, bool shouldAnchor)`
is one method to use.  (Ignore the `shouldAnchor` parameter... or just set it either way.  If I remember right, it's for when you are shift clicking and need to select all of the items between the first and second click.)  The alternative is `SetKeySelected(object key, bool isSelected, bool shouldAnchor)` which is used similarly.

What I won't be able to do is re-introduce that `@bind-Selection` / `SelectionChanged` behavior on the list.  This assumes that the `Selection` is an immutable object and that a new one is being created and passed back to you whenever selection changes.   (At least that's how things are supposed to go in MVU patterns)  Instead, the `Selection` object is going to act like a controller.  What I do need to do is add some change detection logic to the `SelectedItems` property on the `Selection` object.  That way, you could add an actual item to this list and have the UI update...

**Comment by limefrogyank** [comment]
If you're asking why I changed it, this is actually way more like how the react version works and I was finding it incredibly difficult to add other FluentUI components that depended on the react version's way of functioning.

There's a big disconnect between the browser and the blazor c# "back-end".  After the list is drawn on the screen, there is nothing on the javascript/browser side that directly connects back to the c# class objects that were used to draw the list.  So when you're drawing a box around a set of items and trying to identify which items are in the box, you've only got javascript to tell you what objects are there.  I had to re-introduce keys and index numbers to link up the javascript items to the c# class objects.  In any case, that broke a lot of the original functionality... 

I hope to add some of it back in though.

**Comment by MicahN-ISS** [comment]
@NPadrutt @limefrogyank 

OK. with regards to the "}" we can close this issue thread as the bug was fixed with a PR.  

I have solved for everything else this morning. 

1) I just wanted to select an item in the DataList and update my UI with that data I selected on a Single select Selection mode.
Solved:  Yes, thanx to the comments seeing the Selection object is the way to go.  I wired up the event -> `SelectedItem.OnSelectionChanged += new EventHandler(SetSelectedUser);`

2) The other wonky error Value cannot be null. (Parameter 'second')
System.ArgumentNullException: Value cannot be null. (Parameter 'second')
Was due to when I switched to BFUDetailsListAuto the BFUDetailsRowColumn needed the fieldSelector type set (at least this solved the error)

Thanx

**Comment by limefrogyank** [comment]
OK!  I just merged a bunch of PRs (thanks Nino) and added some fixes of my own and setup a new nuget package build.  Since this is badly breaking change, I'm just going to put it out there and hope there are no further big bugs.

In addition to the two methods for setting selected items above, I've added a new method that should be easier:

The `Selection.SelectedItems` property is what you want to use to set which items are selected programmatically.  You can still use the methods if you have keys or index numbers, but the actual items work, too.  You still need to set the `GetKey` callback first, because it needs that to find the key for each item you're adding.

`@bind-Selection` no longer works on ANY list.  It was a leftover from v3 I forgot to remove.  I also removed it from the demo since it would break things.
