### ISSUE TITLE
Can't type in a TextField when a value is bound to it

### ISSUE THREAD

**Issue by NPadrutt** [BlazorFluentUI/BlazorFluentUI#234]
I have a BFUTextField defined something like this:

            <BFUTextField Multiline
                          AutoAdjustHeight
                          Label=@Localizer["DescriptionLabel"]
                          @bind-Value="SelectedProject.Description"
                          @bind-Value:event="OnChange" />

When I now type in this field, I only see the latest letter I type. As soon as I click out of the field, the value disappears altogether.

**Comment by limefrogyank** [comment]
I can't duplicate this behavior.  I added @bind-Value and the event to the Multiline AutoAdjusting TextField on the demo and got a normal result.  It lets me type and I see the value change in another field after I click away.

**Comment by NPadrutt** [comment]
mmh, did you use a specific event?

**Comment by limefrogyank** [comment]
I tried both @bind-Value:event="OnChange" and @bind-Value:event="OnInput"

**Comment by NPadrutt** [comment]
Mmh, that is strange. i have tk see of I can create a reproduction sample. For now I downgraded to 3.6.1 and it works again as expected

**Comment by limefrogyank** [comment]
TextField has been changed since v3.x.  The Forms validation stuff was added.  There's also some logic to decide if it needs to re-render or not.  But it *should* change on a value change.

**Comment by vnbaaij** [comment]
This works now. Don't know since when again but just tested it on V5.2.2 at page https://www.blazorfluentui.net/textFieldPage
