### ISSUE TITLE
Input numeric value

### ISSUE THREAD

**Issue by SteJuventino95** [BlazorFluentUI/BlazorFluentUI#235]
Hi! Is there a way to enter numeric values only in form? Is it correct to use BFUTextField?

Thanks.

**Comment by limefrogyank** [comment]
FluentUI does not have a numeric input... just a string TextField input. 

So `BFUTextField` is the correct one to use.  You can use custom validation to ensure it's a numeric value or you can use Blazor-based Form validation.  We have examples of both on the demo.  

If you would like to extend TextField and add `number` to the `InputType`, feel free and see if it works (and doesn't break anything).  We'd take a PR.
It's too bad that https://caniuse.com/input-inputmode is not supported on Firefox.  That would be a better way to go...
