### ISSUE TITLE
Do not display tooltip if blank

### ISSUE THREAD

**Issue by bobonic** [BlazorFluentUI/BlazorFluentUI#236]
How can we hide the tooltip if text was blank?

`<BFUTooltipHost>
     <TooltipContent>
             @item.Comments
     </TooltipContent>
     <ChildContent>
              <BFUTextField @bind-value="@item.Comments"></BFUTextField>
      </ChildContent>
</BFUTooltipHost>`

![image](https://user-images.githubusercontent.com/2681829/99206169-a8f48500-27f5-11eb-9278-09809286ebc9.png)

**Comment by NPadrutt** [comment]
Couldn't you just surround this with a check if item.comments is empty? Along the lines of: 

```
@if(!string.IsNullOrWhiteSpace(item.Comments))
{
        // ToolTipp code
}
```

**Comment by bobonic** [comment]
it also displays the blank tooltip

**Comment by NPadrutt** [comment]
ah wait. The tooltip wraps the TextField - so my suggestions actually can't work.

**Comment by limefrogyank** [comment]
Looks like we'll have to modify this.  In any case, `Tooltip` is not quite finished, either.  While the display works, you can't yet interact with it.  The bubble disappears when you try to move your mouse and interact with it.  If someone wants to give this a shot, please go for it! :)  

As far as hiding the Tooltip when the content is blank... that's not going to be simple.  Right now, the tooltip contents are a `RenderFragment` and we don't have a way in Blazor to inspect the contents of a `RenderFragment`, so we don't have a way to run logic based off the contents.  Maybe we need to set a property that disables tooltip explicitly.  We could also explicitly set the `TooltipContents` `RenderFragment` as null to disable the tooltip... you'd then have to write your razor code like this somehow:

```
<BFUTooltipHost TooltipContent=@conditionalContent>
        <ChildContent>
        <BFUDefaultButton>Hover to see a tooltip</BFUDefaultButton>
    </ChildContent>
</BFUTooltipHost>

@code{

[Parameter] public string SomeText {get;set;}

RenderFragment conditionalContent;

RenderFragment actualContent = builder => <span>@SomeText </span>;

protected override Task OnParametersSetAsync()
{
    if (string.IsNullOrEmpty(SomeText))
    {
        conditionalContent=null;
    }
    else
    {
        conditionalContent = actualContent;
    }
}
}
```

**Comment by vnbaaij** [comment]
Too much work for edge case
