### ISSUE TITLE
Panel close button "x" becomes "ICE"

### ISSUE THREAD

**Issue by peysaty** [BlazorFluentUI/BlazorFluentUI#237]
Sometimes (1 per 30 times lets say) x becomes ICE

No console 404  loading problem in the browser. Does anyone have an idea what could be broken?

Sorry for the screen, I had to hide panel content

![image](https://user-images.githubusercontent.com/70508227/99239013-c4ae5a00-27fa-11eb-8801-b7b0751899b4.png)

**Comment by limefrogyank** [comment]
I've had that happen a lot when testing locally, but it happens on server-side blazor a lot more than client-side blazor.  Honestly, I'm not sure why it happens.  It's only icons, so it's probably something to do with loading the font icons via CDN while running everything else on localhost.  Not sure though and haven't really pursued it.  I just tried refreshing the server-side demo and couldn't get it to do it... does it happen when published to you?

**Comment by peysaty** [comment]
Yes, happened when published :)

**Comment by vnbaaij** [comment]
Think this is solved with the recent changes we did in handeling of the script and not sending back and forth id's between c# and javascript code. Have not seen it happening anymoreboth serverside nd clientside
