### ISSUE TITLE
NullReferenceException when using OnClick without selection

### ISSUE THREAD

**Issue by GeertvanHorrik** [BlazorFluentUI/BlazorFluentUI#238]
Using the details list without a selection (just want to show a list of items that people can click). This results in a null reference exception, probably because of this line:

https://github.com/BlazorFluentUI/BlazorFluentUI/blob/master/src/BlazorFluentUI.BFUDetailsRow/BFUDetailsRow.razor.cs#L96

**Comment by GeertvanHorrik** [comment]
btw this even happens with DisableSelectionZone == true.

**Comment by GeertvanHorrik** [comment]
A workaround is to create a dummy selection object.

**Comment by vnbaaij** [comment]
Exception is not raised anymore. Not sure when this was fxed.
