### ISSUE TITLE
Request: DetailsList - Inner Navigation

### ISSUE THREAD

**Issue by Cobra86** [BlazorFluentUI/BlazorFluentUI#241]
Is this feature available ?
https://developer.microsoft.com/en-us/fluentui#/controls/web/detailslist/innernavigation

Thanks,

**Comment by limefrogyank** [comment]
Seems like you could replicate it with `ColumnItemTemplate` inside the `BFUDetailsRowColumn`.  Put a link or button that looks like a link and either navigate to a new page or have the logic change the contents of the list.

**Comment by Cobra86** [comment]
Thank you :) i forgot the ColumnItemTemplate. I just tested and its working. thanks again.
