### ISSUE TITLE
NavLinkGroup "CollapseByDefault" applying on every UI update

### ISSUE THREAD

**Issue by Ralms** [BlazorFluentUI/BlazorFluentUI#247]
Hi all, 

I'm using a `Nav` with `NavLinkGroups` to create an easy Accordion, which is working just fine. 
Inside each `NavLinkGroup` I add multiple `Checkbox` elements.

I've noticed that in every UI update, from either have the number of elements change on the foreach or ticking one of the `Checkbox`, the `NavLinkGroup` is applying the `CollapseByDefault` value.
The problem is that when you have `CollapseByDefault` set to `true`, every time something changes inside that group, such as ticking a checkbox, it closes by itself, fairly annoying I might say lol.

Here is my code for reference:

```
<h1>Main title</h1>

<BFUNav>
    <BFUNavLinkGroup Name="Title 1" >
        <BFUStack Tokens=stackTokens>
            @foreach (var item in items)
            {
                <BFUCheckbox Label=@item.DisplayName CheckedChanged=FirstChange />
            }
        </BFUStack>

    </BFUNavLinkGroup>
    <BFUNavLinkGroup Name="Galleries & Pickers" CollapseByDefault="true">
        <BFUStack Tokens=stackTokens>
            <BFUCheckbox Label="Unchecked checkbox (uncontrolled)" CheckedChanged=FirstChange />
            <BFUCheckbox Label="Checked checkbox (uncontrolled)" DefaultChecked="true" CheckedChanged=FirstChange />
            <BFUCheckbox Label="Disabled checkbox" Disabled="true" />
            <BFUCheckbox Label="Disabled checked checkbox" Disabled="true" DefaultChecked="true" />
        </BFUStack>
    </BFUNavLinkGroup>
</BFUNav>*
```

**Comment by limefrogyank** [comment]
I see the problem.  The CollapseByDefault needs to be set once and then not read again.  It's reading it on every render like you said.
