### ISSUE TITLE
[Question] Are we allowed to modify the UI look?

### ISSUE THREAD

**Issue by Codinkat** [BlazorFluentUI/BlazorFluentUI#253]
I would like to know if the license allows to modify the look of the components? If BlazorFluentUI is used in a project but the UI (colors, font, sizing, rounding, etc.) is modified, is this a license violation?

I saw some restrictions about the usage of some icons (Word, Excel...) so I was wondering if Microsoft (or BlazorFluentUI team, haha) could say "hey you modified our official look"

**Comment by limefrogyank** [comment]
You can do whatever you want with our project (BlazorFluentUI).

The only restriction is the icon package that comes from Microsoft. I think they will only come after you if you use their branding icons in an inappropriate way. However, I am not a lawyer, so this is not legal advice 😉

**Comment by Codinkat** [comment]
Ok, great news ;-). I thought FluentUI was a branded UI so you are bound to it.

Thanks!
