### ISSUE TITLE
Navigation vertical scrollbar issue

### ISSUE THREAD

**Issue by allrightsreserved** [BlazorFluentUI/BlazorFluentUI#254]
Hi
I'm currently playing around with your Demo Website and I noticed that the left navigation's vertical scrollbar was disappear when i lunch the program version 4.0.2,but we can see the scrollbar in the version 3.1.6 
That is on the Server Side Demo Site. I haven't tested the wasm version so far.

**Comment by limefrogyank** [comment]
Yeah, this is also something I noticed.  In fact, I can't scroll the menu on mobile.  I don't think there's anything wrong with the library, just the demo.  I'll have to take a look when I have time.  Unless you want to try 😁

**Comment by allrightsreserved** [comment]
hi, I had compared those two version,when I do those steps , this navigation bar and main content are showing normally :
1. replace the code from .net standard 2.1 version to BFULayerHost.Razor as below: 
\<BFUGlobalCS Component="this" CreateGlobalCss=@CreateGlobalCss /\>
\<CascadingValue Value=@this Name="HostedContent"\>
    \<div style=@Style \>
        @ChildContent
        \<div class="ms-LayerHost" @ref="RootElementReference"\>
            \<BFULayerPortalGenerator @ref="portalGeneratorReference" /\>
        \</div\>
    \</div\>
\</CascadingValue\>

2. copy CreateGlobalCss() method to BFULayerHost.Razor.cs from the standard version.
3. using  \<BFULayerHost Style="display:flex; flex-direction: row;width:100vw;height:100vh;overflow:hidden;"\> to wrap the \<Router AppAssembly="typeof(MainLayout).Assembly"\>\</Router \>

The appearance of the scroll bar is the system default style ,in the .net standard 2.1  version 4.0.2 ,the navigation menu's vertical scroll bar can change the surface according to the theme switch button.

**Comment by limefrogyank** [comment]
Thanks, I will try this out soon...

**Comment by allrightsreserved** [comment]
Sorry, my first way will cause other issue, so please try this:
1. add Style="width:100%;height:100vh;overflow:hidden;" in line 95 \<div dir="ltr"\> of BFUTheme.razor.
2. change Style="width:100%;" to Style="width:100%;height:100%;overflow:hidden;" in line 5 \<BFUStack\> of MainLayout of your demo.
Finally we can use the navigation vertical scrollbar again.
thanks alot :)
