### ISSUE TITLE
Toggle Does Not Support Nullable Boolean

### ISSUE THREAD

**Issue by jrolstad** [BlazorFluentUI/BlazorFluentUI#255]
When using the BFUToggle component, there is a mismatch between the Checked value allowing binding to a nullable boolean and the CheckedChanged callback limiting to a non-nullable boolean.

This results in a compile time error when binding the Checked property to models with a nullable bool property, and blocks usage of a bound model with nullable values.

The component should be updated so that it can properly handle nullable Checked values properly.

**Comment by limefrogyank** [comment]
Thanks for the PR.

**Comment by vnbaaij** [comment]
Fixed
