### ISSUE TITLE
Could not find 'BlazorFluentUiRichTextEditor' in 'window'

### ISSUE THREAD

**Issue by bobonic** [BlazorFluentUI/BlazorFluentUI#261]
Im getting this error message when loading

`<BFURichTextEditor ReadOnly="true" />`

![image](https://user-images.githubusercontent.com/2681829/105175901-7b161e80-5b5f-11eb-8d9a-c6fbf89994fe.png)

**Comment by limefrogyank** [comment]
Since RichTextEditor is very immature and is really just a model for how to build your own, I never included the javascript into the main file.  It has it's own file you'll have to reference manually.  (And you'll need quill.js, too.)

```
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <script src="_content/BlazorFluentUI.BFURichTextEditor/richTextEditor.js"></script>
```

**Comment by vnbaaij** [comment]
In the rename branch (V5) the RichTextEditor script is included in the main file
