### ISSUE TITLE
BFUDetailsListAuto Failed to construct 'IntersectionObserver': The provided value is not of type '(Element or Document)'

### ISSUE THREAD

**Issue by chigivigi** [BlazorFluentUI/BlazorFluentUI#262]
I am working in a Blazor ClientSide .Net 5.0 project where I want to add a BFUDetailsListAuto component into my page.  I followed the example shown (https://www.blazorfluentui.net/detailsListAutoPage) but after running my code I get the following error message:

Unhandled exception rendering component: Failed to construct 'IntersectionObserver': The provided value is not of type '(Element or Document)'

I have modified the DataItem class slightly:
```
public class DataItem
    {

        public DataItem()
        {

        }

        public DataItem(int num)
        {
            Key = num.ToString();
            KeyNumber = num;
            DisplayName = "temp" + Key;
            Description = "temp description" + Key;
        }

        public DataItem(string display, string key)
        {
            DisplayName = display;
            Key = key;
        }

        public DataItem(string text, SelectableOptionMenuItemType selectableOptionMenuItemType)
        {
            DisplayName = text;
            Type = selectableOptionMenuItemType;
        }
        public string Key { get; set; }
        public int KeyNumber { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public SelectableOptionMenuItemType Type { get; set; }
    }
```

My DetailsList looks like this:

```
<BFUDetailsListAuto ItemsSource="dataSource"
                    Columns="columnsSource"
                    GetKey=@(x=>x.Key)
                    LayoutMode="DetailsListLayoutMode.Justified"
                    Selection="selection"
                    SelectionMode="SelectionMode.Multiple"
                    />

@code {

    Selection<DataItem> selection = new Selection<DataItem>();
    List<BFUDetailsRowColumn<DataItem>> columnsSource = new List<BFUDetailsRowColumn<DataItem>>();
    List<DataItem> dataSource = new List<DataItem>();
   protected override async Task OnInitializedAsync()
      {
  
            columnsSource.Add(new BFUDetailsRowColumn<DataItem, int>("Key", x => x.KeyNumber) {MinWidth=20, MaxWidth = 70, Index = 0, IsResizable = true });
          columnsSource.Add(new BFUDetailsRowColumn<DataItem, string>("Name", x => x.DisplayName) { Index = 1, MinWidth = 100, MaxWidth = 150, IsResizable = true });
          BFUDetailsRowColumn<DataItem, string> descriptionColumn = new BFUDetailsRowColumn<DataItem, string>("Description", x => x.Description) { Index = 2 };
          columnsSource.Add(descriptionColumn);
          int count = 0;
          for (var i = 0; i < 100; i++)
          {
              count++;
              dataSource.Add(new DataItem(count));
          }
  }
}
```

**Comment by chigivigi** [comment]
Solved it with help from my colleagues. I needed to add the <div data-is-scrollable="true"></div> in my page and put the BFUDetailsListAuto component inside it.

**Comment by msitsoftware** [comment]
Yes exactly the same works for me as well.

**Comment by chigivigi** [comment]
I am having a problem again with my DetailsListAuto component after updating nuget to 5.1.0. My DetailsListAuto does not work if I put a ColumnItemTemplate inside the Column definitions.

Here is the code for my column definition:

    List<DetailsRowColumn<OrganizationResponse>> organizationColumns = new List<DetailsRowColumn<OrganizationResponse>>();

 organizationColumns.Add(new DetailsRowColumn<OrganizationResponse, string>("History Status", x => x.Name) { MinWidth = 60, MaxWidth = 100, Index = 2, IsResizable = false });
        organizationColumns.Add(new DetailsRowColumn<OrganizationResponse, OrganizationResponse>("Name", x => x)
        {
            MinWidth = 200,
            MaxWidth = 300,
            Index = 1,
            IsResizable = true,
            ColumnItemTemplate = item => builder =>
            {
                var i = (OrganizationResponse)item.Value;
                builder.OpenElement(0, "a");
                builder.AddAttribute(0, "href", $"/organizations/{i.AccountId}/home");
                builder.AddContent(1, i.Name);
                builder.CloseElement();
            }
        });

The component looks like this:

<div data-is-scrollable="true" style="height:100%;overflow-y:auto;">
    <BlazorFluentUI.Lists.DetailsListAuto ItemsSource="organizations" Columns="organizationColumns"
        IsVirtualizing="true" Compact="true"
        GetKey=@(x=>x.AccountId)
        LayoutMode="BlazorFluentUI.Lists.DetailsListLayoutMode.Justified"
        Selection="selection"
        SelectionMode="SelectionMode.None" />

</div>

I have an older project with nuget package version 4.0.2 that also has a ColumnItemTemplate but is normally rendered.
The newest version of the nuget package does not solve the issue.

**Comment by vnbaaij** [comment]
Please try with 5.2.1 first.

**Comment by chigivigi** [comment]
I have the same problem with version 5.2.1.

**Comment by chigivigi** [comment]
I tried it in version 5.2.2 and there is the same problem

**Comment by chigivigi** [comment]
This is the error:

![image](https://user-images.githubusercontent.com/30351793/115205477-e5f0da80-a0f9-11eb-81d9-b43435524d87.png)

**Comment by chigivigi** [comment]
This is the error message:
![image](https://user-images.githubusercontent.com/30351793/115212855-3e77a600-a101-11eb-8527-38543da85520.png)

**Comment by vnbaaij** [comment]
There is an example with a `ColumnItemTemplate` in https://www.blazorfluentui.net/detailsListPageBasic. @limefrogyank recently changed it to be abele to show an TextField inside a list. In the source comments he states: "Do NOT use the DetailsRowColumn with two generic parameters.  It does not create an expression that can be used with DynamicAccessor." and that is exactly what you are doing...
I don't know how/if you could work around that. Maybe @limefrogyank can help you with this?

**Comment by tomidix** [comment]
I think it's something with DetailsListAuto component itself because I have the error too and I've managed to reproduce it in Demo project.

Copied Description column definition from DetailsListPageBasic.razor to DetailsListAutoPage.razor (and commented original definition) and the error is reproduced.

![image](https://user-images.githubusercontent.com/7549001/115234716-a3d79100-a119-11eb-9ea4-227a19e4e2c9.png)

**Comment by vnbaaij** [comment]
I have the above described situation ("copied Description column definition from DetailsListPageBasic.razor to DetailsListAutoPage.razor") working in my local demo after applying the commited fix 🎉

**Comment by chigivigi** [comment]
Please publish the new nuget package.

**Comment by vnbaaij** [comment]
V5.2.5 has been pushed to NuGet
