### ISSUE TITLE
Add HyperLink inside List Column

### ISSUE THREAD

**Issue by chigivigi** [BlazorFluentUI/BlazorFluentUI#263]
I have a BFUListDetailAuto component, and I would like to define one column to be filled with hyperlink created dynamicly by passing values from the component source.

Is it possible to add a html element inside this blazor component?

**Comment by limefrogyank** [comment]
Look at using `ColumnItemTemplate`

**Comment by jrolstad** [comment]
@limefrogyank, I am looking for the same functionality.  Do you have an example where this is done as a reference?

**Comment by chigivigi** [comment]
@limefrogyank an example would be of great help if you have it.

**Comment by vnbaaij** [comment]
Look at https://github.com/BlazorFluentUI/BlazorFluentUI/blob/ef1d7bbd4469f947c2813fa57ed27eedb6b8e7e2/Demo/BlazorFluentUI.Demo.Shared/Pages/DetailsListPageBasic.razor#L83-L92
