### ISSUE TITLE
BFUSlider OnChange

### ISSUE THREAD

**Issue by jsaunders92** [BlazorFluentUI/BlazorFluentUI#265]
Hi,

Whenever I try to use `@onchange="@ValueChange"` or `@bind-Value:event="ValueChanged"` I get an exception `Unhandled exception rendering component: Object of type 'BlazorFluentUI.BFUSlider' does not have a property matching the name 'onchange'.`

`@bind-Value=@SliderValue` will work, but that only updates after I've let go of the slider, but I need the value whenever it changes.

It's possible I'm doing something wrong here!

**Comment by vnbaaij** [comment]
Look at https://www.blazorfluentui.net/sliderPage and then the "Controled example". It uses `@bind-Value` and value changes on dragging the slider.

**Comment by jsaunders92** [comment]
Thanks for your reply! Sorry, I should have mentioned, I also used that. It does work, but the value only updates after finishing my dragging, not during the dragging.

**Comment by vnbaaij** [comment]
Strange, any script errors in the console?

**Comment by jsaunders92** [comment]
Nothing unfortunately. So this isn't the intended behaviour then, it should be updating whilst dragging?

**Comment by vnbaaij** [comment]
Yes, it should be updating whilst dragging as can be seen in the mentioned demo page
