### ISSUE TITLE
This Project's NuGet Packages are spamming NuGet.org

### ISSUE THREAD

**Issue by robertmclaws** [BlazorFluentUI/BlazorFluentUI#268]
Hello. I was recently searching NuGet.org for Blazor related packages, and found DOZENS of packages from this project that give no indication of what their purpose is, and serve to do nothing more than clog up the list of Blazor packages.

It is not fair to other developers that your inattention to detail is drowning out the ability to find other great NuGet packages.

For the good of the community, you should HEAVILY consider moving all of these components to a single assembly / project, add package descriptions for the the packages you continue to ship, and de-list all the others. 

Thank you for your consideration.

**Comment by NPadrutt** [comment]
First of all this isn't my repository and I used to prefer the combined package as well. But there is a case to be made for having separated packages, so that every component can be used by itself without having to introduce the whole package into a project.
On a person note: I find your accusing people of "inattention to detail" just because they made a decision that doesn't fit your needs, pretty rude and inappropriate. Especially since in this case they are contributors to the community you seem to want to speak for.

**Comment by robertmclaws** [comment]
I apologize if that comes off as rude, it was not my intention. I'm trying to point out that this project's "needs" make it difficult to find great things to add to Blazor projects. If you take the following into consideration, you might see that this project is not being a good citizen to the larger Blazor community.

First, The "attention to detail" comment is based on the fact that not a single one of the packages has a description of its purpose. It's just 40+ packages in the results that just say "Package Description". Here's an example:

![image](https://user-images.githubusercontent.com/1657085/109407919-d8697080-7952-11eb-8b65-588cfbcd532d.png)
On this screen of 26 NuGet packages, a full 12 have zero context, zero descriptions, and zero instructions. **That's virtually half, just on this screen**

[This search result returns **57 packages**.](https://www.nuget.org/packages?q=blazorfluentui). THREE of them have package descriptions. If you went through the effort to separate your architecture into FIFTY SIX different projects, but haven't taken the time to describe them to potential users, that is the very definition of inattention to detail.

Further, this project used to be called BlazorFabric, which means that this project actually accounts for **6% of the 1500 Blazor** packages on NuGet. So it would be possible to conclude that the only reason to split a system into that many projects would be to overinflate the download statistics and dominate the search results. Which is the very definition of "spammy". 

I would also reasonably assume that was not the intention... but it is the end result.

Finally, there is a cost with processing NuGet packages during build. There is a cost with caching every version of those packages on disk. There is a cost to loading separate assemblies into memory at runtime. The cost of downloading 56 separate assemblies into memory far outweighs the cost of putting all of this into a single assembly. Just wanting to add a Fluent Popup to your project requires downloading 4 dependent BFUI NuGet packages. That's kinda nuts.

Given this information, I believe it's reasonable to ask this project to reconsider whether or not the architecture choices here are actual "needs" and if those choices ultimately cause more problems than they solve.

Once again, thank you for your consideration.

**Comment by vnbaaij** [comment]
Hi, this isn't my repository either but I want to become a contributor. I tend to agree with you on having a single library makes sense. For now that is however not the case. In a fork I'm working on I've already created a (basic) description for every single project/package. I hope to be able to merge that in sometime soon. Hope that alleviates part of your critique.

I would like to point out that having a (Blazor) library split out in multiple packages is definitely not unique to this project. Doing a search for example on 'Syncfusion Blazor' (choose Syncfusion as being one of the major component vendors) on NuGet, also gives a list of 53 packages (with descriptions though 😉). Pretty sure other vendors also have multiple packages although some use their own private feed to 'hide' that but the points you raise on processing, etc. apply to them just as well.

Btw, good that you assume that it is not the intention of this project to overinflate the download statistics and dominate the search results. Again, I'm not the original author but I do know the foundation of this project was originally the Fabric design system from Microsoft which has been renamed by Microsoft to Fluent UI. Renaming the library to follow this change is perfectly normal, I think. Makes sense to de-list the old packages though.

**Comment by Cobra86** [comment]
Microsoft are spamming NuGet too! 
![image](https://user-images.githubusercontent.com/7024154/110315681-7e774380-8001-11eb-8b68-0275905389fb.png)
https://www.nuget.org/packages?q=fluent+

I didn't create this repository and who created this repo and the community are doing great job and all of that for FREE ! 
btw when I searched for blazor. I can't see it on the first page ! and on the second and third pages, it didn't spam and its just showing one or two of the packages (not spamming)! 

Sorry, if i sounded rude but this library are helping me a lot with my project. I don't think they are doing anything wrong and its the only fluent ui library for blazor.

**Comment by vnbaaij** [comment]
The V5 version of this library will consist of only 2 packages. 1 for the core components and 1 for the Lists that have a dependency on DynamicData
