### ISSUE TITLE
BFUPanel should put text into "AriaLabel" instead of "AriaLabelledBy"

### ISSUE THREAD

**Issue by qwindwing** [BlazorFluentUI/BlazorFluentUI#272]
https://github.com/BlazorFluentUI/BlazorFluentUI/blob/ee114285c0750a22de0b6cb9db0e1c06905ccb72/src/BlazorFluentUI.BFUPanel/BFUPanel.razor#L8

Current BFUPanel will generate HTML <code>aria-labelledby="header text"</code>, it should use "AriaLabel" and generate HTML <code>aria-label="header text"</code>.

**Comment by vnbaaij** [comment]
I'm changing this in the V5 branch so that aria-labeledby will point to the id of the label. I think that that is what it is supposed to do (based on what I found in the Fluent UI React samples).

**Comment by qwindwing** [comment]
@vnbaaij Do we have timeline for V5 since my team is trying to fix accessibility bugs for our project which is using BFUPanel?

**Comment by vnbaaij** [comment]
I would say anything between now and two weeks

**Comment by vnbaaij** [comment]
![image](https://user-images.githubusercontent.com/1761079/111325927-6ee4a400-866c-11eb-8403-7758698b4f84.png)
See the HTML source (pic above) from the example at https://white-dune-0ef5c1e03.azurestaticapps.net/panelPage for the result.
