### ISSUE TITLE
NullPointerException on FieldIdentifier.FieldName

### ISSUE THREAD

**Issue by RAN-Vestjylland** [BlazorFluentUI/BlazorFluentUI#273]
https://github.com/BlazorFluentUI/BlazorFluentUI/blob/ee114285c0750a22de0b6cb9db0e1c06905ccb72/src/BlazorFluentUI.BFUDropdown/BFUDropdown.razor.cs#L94

https://github.com/BlazorFluentUI/BlazorFluentUI/blob/ee114285c0750a22de0b6cb9db0e1c06905ccb72/src/BlazorFluentUI.BFUDropdown/BFUDropdown.razor.cs#L116

https://github.com/BlazorFluentUI/BlazorFluentUI/blob/ee114285c0750a22de0b6cb9db0e1c06905ccb72/src/BlazorFluentUI.BFUDropdown/BFUDropdown.razor.cs#L153

Possible solution is to just check if (FieldIdentifier.FieldName != null) on all 3.

**Comment by vnbaaij** [comment]
I'm not seeing this exception in the sample page. Do you have an example of how this is triggered?

**Comment by RAN-Vestjylland** [comment]
I've made a partial code file for the razor component file.

`
    ​public partial class DropDowns
   ​{
       ​private M10Model FormModel { get; set; }
       ​private IList<BFUDropdownOption> DropdownItemsSource { get; set; }

       ​protected override void OnInitialized()
       ​{
           ​FormModel = new M10Model("ID");

           ​DropdownItemsSource = new List<BFUDropdownOption>()
           ​{
               ​new BFUDropdownOption() { ItemType = SelectableOptionMenuItemType.Header, Text = "Something Fruit"},
               ​new BFUDropdownOption() { ItemType = SelectableOptionMenuItemType.Normal, Key = "OrangeID", Text = "Orange"},
               ​new BFUDropdownOption() { ItemType = SelectableOptionMenuItemType.Normal, Key = "AppleID", Text = "Apple"},
               ​new BFUDropdownOption() { ItemType = SelectableOptionMenuItemType.Normal, Key = "BananaID", Text = "Banana"}
           ​};

           ​StateHasChanged();
       ​}

       ​private void DropdownSelectionChanged() ​{ }
   ​}
`

When I do this in the page part, everything works when I click the dropdown items etc.
`
<BFUDropdown DropdownWidth="200" MultiSelect="true" ItemsSource="@DropdownItemsSource" Style="width: 200px;"
                SelectedOptionsChanged="DropdownSelectionChanged" />
`

When I do this in the page part, the null pointer exception occurs when I click items in the dropdown:
`
<EditForm Model="FormModel">
    <BFUDropdown DropdownWidth="200" MultiSelect="true" ItemsSource="@DropdownItemsSource" Style="width: 200px;"
                    SelectedOptionsChanged="DropdownSelectionChanged" />
</EditForm>
`

**Comment by vnbaaij** [comment]
Ok, I added the checks in the rename/V5 branch
