### ISSUE TITLE
TextField binding other simple datatypes of properties to @bind-Value than strings

### ISSUE THREAD

**Issue by RAN-Vestjylland** [BlazorFluentUI/BlazorFluentUI#277]
Hi all,

I'd like to say to begin with I'm really happy with all the components and that I can't wait for v5 to be released!

I really hope that either the current TextField control will be made into a new one that also supports numbers of various type (int, long, double, decimal, float, byte (did i forget some?)). Or that it should be made generic where the type of the property doesn't matter as long as it's a simple datatype.

Thank you advance.

**Comment by vnbaaij** [comment]
Can you explain why you would want/need to use a TextField for these types of numbers? There is already the Blazor native InputNumber<TValue> (forms) component that supports Int32, Int64, Int16, Single, Double and Decimal

**Comment by RAN-Vestjylland** [comment]
This is a framework for having a very specific style and functionality. The BFUTextField (without the BFU prefix) has all the style and functionality that this framework gives - but it ONLY supports to bind a string. But a native Blazor native InputNumber is not yet implemented in this framework. I'm not sure why you want me to even use some native component :-)

**Comment by vnbaaij** [comment]
😁 Ok, I understand. 

I'm not sure if this library should contain 'wrappers' around native components just to get the right style applied. Maybe we should look at providing that through other means (ie CSS classes that you can easily adopt in your own code)? 

Adding this might deviate the functionality of the TextField from its React counterpart but I'm not entirely sure there. Maybe asking if deviating from React is a valid/wanted approach is a good question for the broader community to answer. Can you post it in the [Discussions](https://github.com/BlazorFluentUI/BlazorFluentUI/discussions)?

I'll look into how hard it would be to implement the number types in the meantime.

**Comment by travis-pettry** [comment]
Allowing the text field to bind to numbers would be inline with desktop Fluent UI. Also, it isn't very difficult to add the binding. All you need to do is change the Value to T. Where T is a generic.

**Comment by vnbaaij** [comment]
Yes, that is what I'm working on. The change to generic is indeed not so hard, but it does come with some drawbacks: 1) for every unbound usage, you need to specify the type explicitly (T="string"). 2) I'm getting errors in the demo page on the DefaultValue parameter. It is not being recognized as a string when I set the type to string 😯

**Comment by vnbaaij** [comment]
@travis-pettry, @RAN-Vestjylland please look at https://github.com/BlazorFluentUI/BlazorFluentUI/discussions/280 and give feedback. Closing this issue for now.

**Comment by vnbaaij** [comment]
TextFieldNumber is now added as a component to V5.1. See #280 and WhatsNew.md for more information.
