### ISSUE TITLE
DropDown Multiselect can't select when clicking to right of label

### ISSUE THREAD

**Issue by Tailslide** [BlazorFluentUI/BlazorFluentUI#281]
I verified the behaviour is the same on the latest dev nuget.
If you go to https://www.blazorfluentui.net/DropdownPage

You can select an item from the dropdown in single select mode by clicking anywhere in the area that highlights on hover.
For multiselect, it behaves differently and only selects if you click the label but not the highlighted space to the right of the label.

**Comment by vnbaaij** [comment]
I see it was already like that in the 3.0 version (look at demo at https://blazorfluentui.azurewebsites.net/dropdownPage). Will keep this open to take a look at at a later stage.
Would be great if you can solve and submit a PR for this!

**Comment by limefrogyank** [comment]
This is due to the way multiselect uses a checkbox component instead of a button component (for single select).  Yeah, this would be a nice fix.  Not sure if you could just expand the label area... css is always tricky.
