### ISSUE TITLE
[Potential Bug] DatePicker failing to open in BlazorServer followed by NullReferenceException

### ISSUE THREAD

**Issue by gstew45** [BlazorFluentUI/BlazorFluentUI#284]
Cannot get DatePicker to show within BlazorServer. 

When clicking the DatePicker nothing happens and as soon as you try navigate away from the page a NullReferenceException is thrown.

Defined DatePicker like this:
```
<DatePicker AllowTextInput="false"
				Style="max-width:300px; margin:0 0 15px 0;"
				Placeholder="Select a date..."
				@bind-Value=@selectedDate1
				FirstDayOfWeek=@DayOfWeek.Sunday />

@code {
	DateTime? selectedDate1;
} 
```

Nothing happens, then when navigating away from the page this exception appears in the Console output

`blazor.server.js:19 [2021-03-29T22:00:45.537Z] Error: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BlazorFluentUI.Layer.DisposeAsync()
   --- End of inner exception stack trace ---`

I am unsure If I am doing something wrong here, all other BFU components I am using work as expected but can't understand why this one isn't.

**Comment by limefrogyank** [comment]
Maybe related to #285?  I'll check

**Comment by limefrogyank** [comment]
I think it may have to do with prerendering again.  I made a change in LayerPortalGenerator's RemoveHostedContentAsync method that now checks for the presence of a portalfragment before trying to remove it from a list.  That may have been what was throwing an error for you.   I'm not sure... I couldn't make DatePicker throw any errors on my side.
