### ISSUE TITLE
DetailsList issue when use with Pivot tab

### ISSUE THREAD

**Issue by jaisondthomas** [BlazorFluentUI/BlazorFluentUI#285]
Steps to reproduce the issue.(I have used Basic detailslist code and pivot large link example code from demo site)

Step 1 - press the "click me first " tab
Step 2 - then press the "click me second" tab
I have a Detailslist control inside the first tab

Error message - BlazorFluentUI.Lists.DetailsList`1.DisposeAsync()
I am using the new version( BlazorFluentUI V5.1.0.0 ) and doing Blazor server-side

<div>
    <Pivot AriaLabel="Large Link Size Pivot Example" LinkSize=PivotLinkSize.Large>
        <PivotItem HeaderText="My Files">
            <Label>Pivot #1</Label>
        </PivotItem>
        <PivotItem HeaderText="Recent">
            <Label>Pivot #2</Label>
        </PivotItem>
        <PivotItem HeaderText="Click me first">
            @*DetailsList demo page code*@
            <div data-is-scrollable="true" style="height:400px;overflow-y:auto;">
                <DetailsList ItemsSource="InputList"
                             Columns="Columns"
                             GetKey=@(item=>item.Key)
                             LayoutMode="DetailsListLayoutMode.Justified"
                             TItem="DataItem"
                             OnItemInvoked="OnClick"
                             Selection="selection"
                             SelectionMode="SelectionMode.Single">
                </DetailsList>
            </div>
        </PivotItem>

        <PivotItem HeaderText="Click me second">
            <Label>Pivot #3</Label>
        </PivotItem>
    </Pivot>
</div>

**Comment by limefrogyank** [comment]
I found the error.  The default value for the layer registration was zero instead of -1.  DisposeAsync is getting called twice (I *think* because of pre-rendering) and it was thinking it had to dispose the javascript object twice.  Now it only does it once.
