### ISSUE TITLE
Could not find 'FluentUIBaseComponent.initializeFocusRects'

### ISSUE THREAD

**Issue by silveyy** [BlazorFluentUI/BlazorFluentUI#289]
Followed the instructions for server side blazor to add to our existing application and get this error on load of our app.

[2021-04-12T23:40:00.253Z] Error: Microsoft.JSInterop.JSException: Could not find 'FluentUIBaseComponent.initializeFocusRects' ('FluentUIBaseComponent' was undefined).
Error: Could not find 'FluentUIBaseComponent.initializeFocusRects' ('FluentUIBaseComponent' was undefined).
    at https://localhost:5001/_framework/blazor.server.js:1:67390
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:5001/_framework/blazor.server.js:1:67350)
    at v (https://localhost:5001/_framework/blazor.server.js:1:69092)
    at https://localhost:5001/_framework/blazor.server.js:1:70038
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:1:70011)
    at https://localhost:5001/_framework/blazor.server.js:1:26293
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:26263)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorFluentUI.FluentUIComponentBase.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
[2021-04-12T23:40:00.257Z] Information: Connection disconnected.

**Comment by vnbaaij** [comment]
Sorry, but how are we supposed to help you with this little information? This is not how open source works. What version of Blazor are you using? Which component(s) and what version did you install? Show us how the instructions were implemented, etc...Then we can maybe reproduce and help.

**Comment by silveyy** [comment]
Fair, was hoping maybe this was a FAQ or there might be something obvious around "make sure you do this or aren't doing that. 

We have an existing Blazor app based on 5.0, it's working well and running in production. Trying to do some testing to consume this set of Fluent controls so...

I think I've  followed all the steps outlined in server blazor for using these components but I just went through the diff of my changes and here's what they are:

1. Added PackageReference to these components
![image](https://user-images.githubusercontent.com/39961687/114587014-19cf8a00-9c3a-11eb-85de-0e33a4504770.png)
2. Added Theme element to app.razor file.
3. Added Using statements to _Imports.razor
4.  Added services.AddBlazorFluentUI() to ConfigureServices
5. Added stylesheet reference for fabric.min.css
6. Replaced our loading component HTML with a fluent spinner control 
The fluent spinner appears, but the app faults with the error listed in original posting. 

![image](https://user-images.githubusercontent.com/39961687/114588117-2e605200-9c3b-11eb-9619-fa3dd7b36916.png)

**Comment by limefrogyank** [comment]
This might be very obvious, but try clearing your browser cache.  I've run into outdated cache issues frequently when developing Blazor stuff.

**Comment by silveyy** [comment]
Thank you for the suggestion, I just tried that and still seeing this error.  What content did you suspect was cached? Here's what I'm seeing in sources in the browser dev tools.... 

![image](https://user-images.githubusercontent.com/39961687/114590731-fdcde780-9c3d-11eb-877b-70297ed57f74.png)

**Comment by vnbaaij** [comment]
Could it be that it is trying to use the BlazorFluentUI script and components before it is all actually initialized? I'll try it in my local server version later today.

**Comment by silveyy** [comment]
Our app has quite a few different layered components, with a lot of JS interop as well. I'm wondering if we are somehow influencing this initialization... If you have thoughts on how we can further troubleshoot let me know and I'll give it a shot. I'll try to dig in a little deeper.

**Comment by silveyy** [comment]
**Issue resolved.**

I noticed I referenced version 5.1.0 but there was a 5.2.0 version available. After updating the version this issue is resolved so it seems the JS isolation implementation here has resolved this issue.
