### ISSUE TITLE
DetailsListAuto throws a tantrum

### ISSUE THREAD

**Issue by RAN-Vestjylland** [BlazorFluentUI/BlazorFluentUI#290]
I'm not sure if this is a bug or i'm just having wrong code. So I hope to clarify what I have done with the following code and why it won't work for me. (Thank you in advance)

Razor part:
`<DetailsListAuto ItemsSource="StagnationOptions"
IsVirtualizing="true"
TItem="DataItem"
Compact="true"
Columns="StagnationColumnSource"
GetKey="@(x => x.Key)"
LayoutMode="DetailsListLayoutMode.FixedColumns"
Selection="StagnationOption"
SelectionMode="SelectionMode.Single" />
`

Code part (Variables):
`
private Selection<DataItem> StagnationOption { get; set; }
private IList<DataItem> StagnationOptions { get; set; }
private IList<DetailsRowColumn<DataItem>> StagnationColumnSource { get; set; }
`

Code part (Filling with values):
`
StagnationOptions = new List<DataItem>();
StagnationOptions.Add(new DataItem("true", "Ja"));
StagnationOptions.Add(new DataItem("false", "Nej"));
`
`
StagnationColumnSource = new List<DetailsRowColumn<DataItem>>();
StagnationColumnSource.Add(new DetailsRowColumn<DataItem, string>("Text", x => x.Text) { Index = 0 });
`

This is the error that shows in the console when running:
![2021-04-15 08_59_30-VES TBS3 (Running) - Microsoft Visual Studio](https://user-images.githubusercontent.com/78351622/114827474-0999e500-9dc9-11eb-8b6a-4a410866025a.png)

And this is how it looks with the error:
![2021-04-15 09_00_07-VES TBS3](https://user-images.githubusercontent.com/78351622/114827620-377f2980-9dc9-11eb-9acd-383ddbc43861.png)

**Comment by vnbaaij** [comment]
Sorry, but I introduced a bug here. It has to do with th e JavaScript isolation I added. I forgot to delete the '.' in the call to `addViewPort`. Fix is on its way.

**Comment by vnbaaij** [comment]
Fixed in V5.2.1

**Comment by RAN-Vestjylland** [comment]
Same way as above with version 5.2.1 this error occurs now:
![2021-04-15 15_37_37-VES TBS3](https://user-images.githubusercontent.com/78351622/114878564-ac218a80-9e00-11eb-96e0-c01246d55a59.png)

**Comment by vnbaaij** [comment]
You're probably missing a `<div>` somewher. See #262 for info

**Comment by RAN-Vestjylland** [comment]
When the component is commented out everything else works fine:
![2021-04-15 15_44_20-VES TBS3 - Microsoft Visual Studio](https://user-images.githubusercontent.com/78351622/114879522-919be100-9e01-11eb-873f-41dc1135ea55.png)

When having it in, that error shows:
![2021-04-15 15_44_36-VES TBS3 - Microsoft Visual Studio](https://user-images.githubusercontent.com/78351622/114879573-9d87a300-9e01-11eb-9e0d-832c38f85afa.png)

**Comment by vnbaaij** [comment]
See my previous comment andread #262. You need a <div data-is-scrollable="true"></div> surrounding the  DetailsListAuto component
.

**Comment by RAN-Vestjylland** [comment]
I'm not sure how convenient this is, but if IsHeaderVisible is set to false, the component throws a null pointer exception when not having the Columns attribute set.

**Comment by tomidix** [comment]
Regarding this, you should probably unlist 5.2.0 due to such bug and leave only 5.2.1.. I also have some disposable bug which is introduced in 5.2.0 / 5.2.1 but I'll open another issue..
