### ISSUE TITLE
Labels placement

### ISSUE THREAD

**Issue by RAN-Vestjylland** [BlazorFluentUI/BlazorFluentUI#291]
I have a request for placement of labels of all the components. It would be awesome if there could be added an attribute to place the label either above or to the left of the component it belongs to.

Default:
![2021-04-15 09_05_42-VES TBS3](https://user-images.githubusercontent.com/78351622/114828121-d0ae4000-9dc9-11eb-928d-cc61c655b741.png)

Left label with width of label defined:
![2021-04-15 09_05_42-VES TBS3 Left label](https://user-images.githubusercontent.com/78351622/114828542-503c0f00-9dca-11eb-9357-c104104504e5.png)

**Comment by vnbaaij** [comment]
THis is not something that is available in the React version. As we follow its functionality, this will probably not be added.
