### ISSUE TITLE
DetailsListAuto throws a disposable error

### ISSUE THREAD

**Issue by tomidix** [BlazorFluentUI/BlazorFluentUI#292]
With introduction of nuget 5.2.1,
On page which uses eventhandlers and implements IDisposable so it could unsubscribe from the events.. 
BlazorFluentUI.Lists.DetailsListAuto throws an error:
**TypeError: Cannot read property '_isDisposed' of undefined**
![image](https://user-images.githubusercontent.com/7549001/114892252-e1cc7080-9e0c-11eb-8eb9-89ea75861375.png)

When component is deleted/commented out from code - page works.
When package is reverted to v5.1.0 - page works.
Tried to remove IDisposable implementation on page, didn't help so I guess that doesn't matter.

**Comment by chigivigi** [comment]
I have the same problem.

**Comment by vnbaaij** [comment]
Fixed in V5.2.2 (I **hope**)

**Comment by tomidix** [comment]
I can confirm that it works now. Thanks for fast fixing the issue.
