### ISSUE TITLE
Theme Documentation

### ISSUE THREAD

**Issue by travis-pettry** [BlazorFluentUI/BlazorFluentUI#294]
The documentation for changing themes seems to be out of date. When I updated my nuget packages to version 5.x I found that the theming does not work anymore. When I load a page the DropDown throws a null reference on SetStyle.

**Comment by vnbaaij** [comment]
That might very well be the case. A lot has changed internally with the move to version 5.x. Don't know when we will get around to this, but we DO accept pull requests...
