### ISSUE TITLE
DetailsList (both basic and auto) can't use whole row model for columnItemTemplate

### ISSUE THREAD

**Issue by tomidix** [BlazorFluentUI/BlazorFluentUI#298]
This bug is introduced in v5.* and latest 5.2.5 still has the problem.
This is kind of continuation of problems which I wrote here: https://github.com/BlazorFluentUI/BlazorFluentUI/issues/262#issuecomment-822421626

So, now to modify my example from there just a little bit, and make a real use case scenario where I need a url in a column and I need two properties from row item so I tried to send whole DataItem:
![image](https://user-images.githubusercontent.com/7549001/116119974-54680680-a6bf-11eb-97a6-c25e886beef1.png)

This code throws an error like this one:
![image](https://user-images.githubusercontent.com/7549001/116120408-c93b4080-a6bf-11eb-993c-cb3d538b4bf7.png)

(just to note, this was working perfectly in v4.*)

**Comment by limefrogyank** [comment]
Try to create your DetailsRowColumn with only one generic parameter:
```
columnsSource.Add(new DetailsRowColumn<DataItem>("Url", x=> x)
{
   // etc...
}
```
The overload that uses one generic creates an `Expression<Func<T>>` rather than a `Func<T>`.  I think that may be your problem.

**Comment by limefrogyank** [comment]
FYI, I am open to new idea on how to do type safety here.

**Comment by limefrogyank** [comment]
Making changes to this here:  
https://github.com/BlazorFluentUI/BlazorFluentUI/pull/299

**Comment by chigivigi** [comment]
I tried out the demo project in branch DetailsListFix, but I can't use open and closing tabs for the column item template. For an example I want to read the display name from the DetailsList source and use it as the text for the Link component, but I cannot put it between Link open and closing tabs. Text and closing Link tab are interpreted as an error: Invalid initializer member declarator.

This is the code snippet:
`CustomColumns.Add(new DetailsRowColumn<DataItem, DataItem>("Links", x => x)
        {
            Index = 3,
            ColumnItemTemplate = obj => @<Link Href="@obj.Description">@obj.DisplayName</Link>
        });`

**Comment by vnbaaij** [comment]
Can you try with using BlazorFluentUI.Link instead of just Link

**Comment by chigivigi** [comment]
It works after using BlazorFluentUI.Link instead of Link. 
Thank you for your help @vnbaaij.

@limefrogyank please publish the nugget update if possible.

**Comment by vnbaaij** [comment]
V5.2.7 is being pushed to NuGet as we speak

**Comment by chigivigi** [comment]
Do you know how to correctly pass a method on onclick event in custom item template:

`CustomColumns.Add(new DetailsRowColumn<DataItem, DataItem>("Button", x => x)
        {
            Index = 3,
            ColumnItemTemplate = obj => @<BlazorFluentUI.PrimaryButton OnClick="@(()=>TestMethod(obj))">@obj.DisplayName</BlazorFluentUI.PrimaryButton>
        });`

The error message is: cannot convert lambda expression to type 'bool' because it is not a delegate type
