### ISSUE TITLE
Suggestion to support For on labels separate from component without label set

### ISSUE THREAD

**Issue by RAN-Vestjylland** [BlazorFluentUI/BlazorFluentUI#304]
Suggestion from me is that when a label is set separately For should be able to reference a component. But it's not possible to set the ID specifically on the component. So the suggestion is that a new attribute could be added to the components ForID="ThisSpecificComponent" for instance and then the Label component has a For="ThisSpecificComponent" so the focus on label click still works.

**Comment by vnbaaij** [comment]
Can you elaborate with an example. Not really sure I fully understand what you want/are trying to accomplish.

Also, if you have suggestions/wishes, please use the Discussions function first. That is the area where we can exchange ideas etc. Lets keep the Issues area for issues. Thanks

**Comment by RAN-Vestjylland** [comment]
https://github.com/BlazorFluentUI/BlazorFluentUI/discussions/306
