### ISSUE TITLE
DetailsList Column Item Template Primary Button OnClick method error

### ISSUE THREAD

**Issue by chigivigi** [BlazorFluentUI/BlazorFluentUI#305]
I am using the demo project to add a button action inside details list basic page component. Inside the details list basic page razor I added a new column for a primary button component and added a new method action that the button uses.

Code snippet:

        // Do NOT use the DetailsRowColumn with two generic parameters.  It does not create an expression that can be used with DynamicAccessor.
        CustomColumns.Add(new DetailsRowColumn<DataItem>("Key", x => x.KeyNumber) { MaxWidth = 70, Index = 0 });
        CustomColumns.Add(new DetailsRowColumn<DataItem>("Name", x => x.DisplayName!) { Index = 1, MaxWidth = 150, OnColumnClick = this.OnColumnClick, IsResizable = true });
        CustomColumns.Add(new DetailsRowColumn<DataItem,DataItem>("Notes", x => x)
        {
            Index = 2,
            // Two issues:
            // 1.  Using a value type directly with a RenderFragment prevents any updating of the original value since it is copied to this RenderFragment.
            //     Instead, the output of ColumnItemTemplate is a DynamicAccessor<object> that has a single property of Value.  This way, changes are passed back
            //     to the original property because DynamicAccessor creates a setter from your original getter (the field selector).
            // 2.  Blazor cannot do type conversions directly with binding yet.  Since the output (of DynamicAccessor's Value) is an object, we need to manually 
            //     create the callback that sets the Value from the change.  We can't use generics (easily) because they would all have to be the same type.
            ColumnItemTemplate = obj => @<TextField @bind-Value="obj.Description" @bind-Value:event="OnChange"/>
            //ColumnItemTemplate = description => builder =>
            //{
            //    builder.OpenComponent<TextField>(0);
            //    builder.AddAttribute(1, "Value", description.Value);
            //    builder.AddAttribute(2, "ValueChanged", EventCallback.Factory.Create<string>(this, changedText =>
            //    {
            //        description.Value = changedText;
            //    }));
            //    builder.CloseComponent();
            //}

        });

        CustomColumns.Add(new DetailsRowColumn<DataItem, DataItem>("Button", x => x)
        {
            Index = 3,
            ColumnItemTemplate = obj => @<BlazorFluentUI.PrimaryButton OnClick="@(()=>TestMethod(obj))">@obj.DisplayName</BlazorFluentUI.PrimaryButton>
        });

The method action I am using is this:

`
private void TestMethod(DataItem dataItem)
  {
    Console.WriteLine("test " + dataItem.DisplayName);
  }
`

The problem is that I am having trouble defining the method type. The button inside the details list would be used to call async actions on the data that will modify the row value or delete it from the data that the list uses. 
It is showing me a strange error message: Error CS1660: cannot convert lambda expression to type 'bool' because it is not a delegate type.

The error message underlines the value for the OnClick parametar of my Primary Button inside the Custom Item Template , in this case calling my TestMethod and passing the row value.

How do I modify my TestMethod or call the method inside the Primary Button OnClick parameter ?

There is an additional error message when the method is making an async http client get request:
Error CS1662: Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type

**Comment by vnbaaij** [comment]
This works when you put it in the correct spots in `DetailsListPageBasic`

(`selection` is defined at top of `OnInitialized`)
It is not perfect because now when you click a button, the same line gets selected in the other grid as well. Think that has to do with the `this` part of the `EvenCallBack.Factory.Create` which I dont know how to adjust to target a specific DetailsList. Tried to solve it with a @ref on the component but that gave runtime error 'Value cannot be null'

`var callback = EventCallback.Factory.Create<MouseEventArgs>(this, arg =>
        {
            OnClickHandler(selection.GetItems().First<DataItem>().Key);
        });
        CustomColumns.Add(new DetailsRowColumn<DataItem, DataItem>("Button", x => x)
        {
            Index = 3,
            ColumnItemTemplate = obj => builder =>
            {
                builder.OpenComponent<DefaultButton>(0);
                builder.AddAttribute(1, "Text", obj.Key);
                builder.AddAttribute(2, "OnClick", callback);
                builder.CloseComponent();
            }
        });


        int count = 0;
        for (var i = 0; i < 100; i++)
        {
            count++;

            InputList.Add(new DataItem(count));
        }

        base.OnInitialized();
    }

    private void OnClickHandler(string item)
    {
        Console.WriteLine($"Button on line {item} was clicked");
    }`
