### ISSUE TITLE
[Feature]DetailsList / DetailsListAuto - OnSelectionChange needed

### ISSUE THREAD

**Issue by tomidix** [BlazorFluentUI/BlazorFluentUI#319]
For all type of selectable grids, if selectionmode!=none we need OnSelectionChanged event.
That's for easily enabling/disabling some buttons depending on selection

**Comment by horaciodiez** [comment]
I think the answer is here. You have OnItemInvoked. 
I hope this help.

"List, DetailsList, GroupedList

A big change is that OnItemInvoked will only work when SelectionMode is set to None. If you need Selection active and the invoke item function to work at the same time, you can attach an event handler to the Selection.OnSelelectionChanged event or subscribe to the SelectionChanged observable."
