### ISSUE TITLE
Invalid JSON on Load

### ISSUE THREAD

**Issue by SSgumS** [BlazorFluentUI/BlazorFluentUI#320]
Hello

When website is loading, lots of Invalid JSON appears in the console. We can see them on the demo website as well (for example: https://www.blazorfluentui.net/commandBarPage) (They are so much that sometimes it affects performance). Unfortunately I couldn't figure out what is the reason of the problem...

Note: Maybe the other issue that I was working on it  (#315) basically is related to this :? (As a side note, I could reproduce that issue on the demo. But I could overcome to it by fixing some validation issues on TextField (I will open a pull request later))

**Comment by vnbaaij** [comment]
It seems this is only happening in the WebAssemly version of the demo. I have absolutely no idea what i causing this and where to start looking for a fix. Any help would be greatly appreciated!

**Comment by Cobra86** [comment]
On my project, Its happening on the blazor server and just the CommandBar. I've investigated this morning. I think the issue in the FocusZone component. I'm not 100% sure, the error gone after i commented the FocusZone component in the overflow. 
Also, I've debugged the javascript and the error is happening after something calling the OnResizedAsync.
![image](https://user-images.githubusercontent.com/7024154/119903092-18cf8f00-bf40-11eb-9d46-2c9d45c23a22.png)
also there is two functions with name OnResizedAsync in the ResizeGrou.razor.cs. i know its commented but before .net 5 i had issue with blazor where it was running commented code.
![image](https://user-images.githubusercontent.com/7024154/119903743-102b8880-bf41-11eb-812a-0f6524ebf289.png)

**Comment by vnbaaij** [comment]
I've removed the commented code (just to be sure) and I also tried removing the `FocusZone` from the `OverflowSet`. Dit not help. Still getting all the errors in the WebAssembly variant when reloading the `commandBarPage`

**Comment by Cobra86** [comment]
I commented the function GrowDataUntilItDoesNotFit in the GetNextStateAsync and I didn't get any errors. but it doesn't make sense to me because its not passing the content to render. I might be wrong.
![image](https://user-images.githubusercontent.com/7024154/119974731-ec9e2780-bfac-11eb-871a-0e532edc9639.png)

I'm 100% sure the issue with the ResizeGroup component.
Maybe because the same OnResizedAsync function with [JSInvokable] attribute in different classes ? 
![image](https://user-images.githubusercontent.com/7024154/119981084-1d825a80-bfb5-11eb-8074-aee48498f658.png)

**Comment by vnbaaij** [comment]
It is not in the `OnResizedAsync` calls. I can see them being called after each other.

I can't reproduce the errors not being thrown when commenting out the method ou mention. Agree that is is most probably caused somewhere in `ResizeGroup`

**Comment by Cobra86** [comment]
I've commented this two lines in the GetNextStateAsync function and it fixed the issue and the commandbar is working fine. I didn't test everything, I just tested the button click and overflow menu.

![image](https://user-images.githubusercontent.com/7024154/120000707-0189b380-bfcb-11eb-9d32-f6a8dc4c4c1a.png)

**Comment by vnbaaij** [comment]
Still seeing them in WebAssembly version...;(
