### ISSUE TITLE
CommandBar is erroring when resizing the browser window.

### ISSUE THREAD

**Issue by Cobra86** [BlazorFluentUI/BlazorFluentUI#324]
When I resize the browser window, the commandbar is throwing JavaScript error in the browser console and nothing in the event log.
I tired to create new project and its the same issue. i'm using 5.3.1.
![image](https://user-images.githubusercontent.com/7024154/119731830-544e5880-be6f-11eb-8ba0-70536c7fcad4.png)

![image](https://user-images.githubusercontent.com/7024154/119732023-94154000-be6f-11eb-8c4d-0c6bc3e73e8c.png)

**Comment by vnbaaij** [comment]
This is the same error as reported in #320. Closing this one.
