### ISSUE TITLE
JsonException when components are shown/hidden quickly

### ISSUE THREAD

**Issue by alexnoddings** [BlazorFluentUI/BlazorFluentUI#325]
I'm encountering an issue where BFU is crashing when elements are shown/hidden when navigating around my app. 

I put together a [minimal repro](https://github.com/alexnoddings/BfuCrash) to showcase the issue, which happens across a variety of components. The issue is primarily occuring when navigating between pages, but the repro causes it by showing/hiding a component quickly. This isn't done in my app, but is much quicker to cause the issue than just clicking around until it happens.

The application uses BFU on Blazor Server 5.0. The following error is produced in the console:
```
Error: System.Text.Json.JsonException: Invalid JSON
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS(JSRuntime jsRuntime, String arguments)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<>c__DisplayClass43_0.<EndInvokeJSFromDotNet>b__0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<InvokeAsync>b__8_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.EndInvokeJSFromDotNet(Int64 asyncCall, Boolean succeeded, String arguments)
```

**Comment by crjc** [comment]
I've also noticed this problem when clicking onto a new tab with the pivot component. It seems that this problem only started from 5.2.8, everything works fine for me in 5.2.7

**Comment by alexnoddings** [comment]
It seems like the issue stems from the cancellation tokens. When a component's [`DisposeAsync`](https://github.com/BlazorFluentUI/BlazorFluentUI/blob/781b0c66b87dc8a85208b884784f63437c74b672/src/BlazorFluentUI.CoreComponents/BaseComponent/FluentUIComponentBase.cs#L149) is called, the `cancellationTokenSource.Token` get cancelled. If the import in [`OnAfterRenderAsync`](https://github.com/BlazorFluentUI/BlazorFluentUI/blob/781b0c66b87dc8a85208b884784f63437c74b672/src/BlazorFluentUI.CoreComponents/BaseComponent/FluentUIComponentBase.cs#L73) hasn't finished before being cancelled, a `JsonException` exception is thrown after `OnAfterRenderAsync` has returned.

**Comment by vnbaaij** [comment]
Thanks for this fix!! Itegrating it into release now.
