### ISSUE TITLE
DetailsListAuto column resizing does not work 

### ISSUE THREAD

**Issue by marktoman** [BlazorFluentUI/BlazorFluentUI#332]
When running the repo (V5.3.3.0) directly, it works, but when installing the same version from nuget, it does not.

Steps to reproduce:

1. Run:
```
dotnet new blazorserver
dotnet add package BlazorFluentUI.CoreComponents
dotnet add package BlazorFluentUI.ListComponents
```

2. Add  `services.AddBlazorFluentUI();` to `ConfigureServices`
3. Add `@using BlazorFluentUI` and `@using BlazorFluentUI.Lists` to `_Imports.razor`
4. Copy files from Demo:
```
cp ..\BlazorFluentUI\Demo\BlazorFluentUI.Demo.Shared\Pages\DetailsListAutoGroupedPage.razor .\Pages
cp ..\BlazorFluentUI\Demo\BlazorFluentUI.Demo.Shared\Models\DataItem.cs .\Data
cp ..\BlazorFluentUI\Demo\BlazorFluentUI.Demo.Shared\Models\Lorem.cs .\Data
```
5. Remove the namespace declaration from `DataItem.cs` and `Lorem.cs` (i.e. move to global)
6. Add `using BlazorFluentUI;` to `DataItem.cs`
7. Remove `<Demo></Demo>`  in `DetailsListAutoGroupedPage.razor`
8. Wrap content of `App.razor` in `<Theme></Theme>`
9. `dotnet run`
10. Open https://localhost:5001/detailsListAutoGroupedPage

Try to resize the Description column on the first table

**Comment by marktoman** [comment]
Found it, I forgot to add `<LayerHost />` to `App.razor`.

**Comment by vnbaaij** [comment]
Good catch 👍 I'll see if I can add some more info in the docs.
