### ISSUE TITLE
DetailListAuto makes the page not responding when large number of items are loaded

### ISSUE THREAD

**Issue by tomidix** [BlazorFluentUI/BlazorFluentUI#334]
**Describe the bug**
When our grid has large number of items (we have around 200 items with 6-7 columns), whole page gets unresponsive for a long time (around 5 minutes). Like some looped events are triggering in the background. When it happens, dropdowns and other components doesn't react at all. It happens as soon as grid gets the data, (in our solution get is triggered by button so it's clearly visible when it happens)

**To Reproduce**
Edit the DetailListAuto demo page to have even more records (I used 300, because it's even more visible)..
After loading of the page, check the dropdown at top that it works, and click on the blank part of the page to collapse it back.
Scroll the grids down just to load some items, and back.. Then go up the page and try to change the same dropdown again..
You'll see that it won't react or will react with a big delay..
(also if you disable virtualization hyper-scrolling gets laggy, which is not the case once the grid loading finishes)

**Expected behavior**
The grid should not take so much resources that the other components gets unresponsive, even with the large number of records

**Desktop environment:**
 - Latest Edge (91.0.864.59) and Chrome (91.0.4472.124)
 - Windows10 up to date (20H2, build: 19042.1052)
 - i7 8650U in high performance mode @3.4Ghz
 - 16GB ram

**Comment by tomidix** [comment]
@limefrogyank @vnbaaij any news on this? or at least a guess what could be the cause?

**Comment by vnbaaij** [comment]
I'm taking a look as we speak. I think the problem is  (partialy) caused by the fact that component is not using the native Virtualize component yet. In general the ...List... components are quite advanced and I don not understand all the code that makes them tick. Maybe @limefrogyank can take a closer look?

**Comment by limefrogyank** [comment]
I'll try to get to it this week... but there are many reasons it's so complicated.  I would love to use the native Virtualize component.  I think I didn't use it because I rewrote the whole thing before it got officially released.  It might be time to go back and look at that.  However, the complexity comes from the component handling sort, filter, and selection itself.  If we made the user do it, it would be a lot easier for us, but less attractive of a component.
 
There's obviously some rendering redundancies going on.  It's hard to track it all down.  I'll try and take a look soon.

**Comment by limefrogyank** [comment]
At a quick glance, looks like way too many JS interop calls (you can see them in the websocket connection if running serverside).  I'll narrow it down...

**Comment by limefrogyank** [comment]
In case anyone wants to try figuring out:

I actually incorporated the code of the native `Virtualize` into the `List` component.  It's doing almost exactly what `Virtualize` does.  The reason I copied it was so I could make the component encapsulate all of the items into a container that included the index as a property.  This was so I could use the index for selection.  So I'm fairly certain the basic `List` is working fine.  There's something wrong with DetailsList (or maybe SelectionZone).

**Comment by limefrogyank** [comment]
One of the problems with DetailsList is the number of TaskCancelledExceptions coming from the DetailsRows.   However, this should only affect it in Debug mode.  In Release mode, it is faster.  However, the performance is still not great.  I'll try overriding ShouldRender().

**Comment by limefrogyank** [comment]
Should be greatly sped up with https://github.com/BlazorFluentUI/BlazorFluentUI/commit/8669f0c21def4d9973797af19a612d3d02e22239

But try it in release mode when you're testing for speed...

**Comment by limefrogyank** [comment]
Yeah, the demo works better, too.  
https://www.blazorfluentui.net/detailsListAutoPage

I'm noticing that multiple select is not working via mouse.  (The button that causes 3+4 to be selected does work.)

**Comment by limefrogyank** [comment]
Sorry for the spam, but maybe someone can copy this work to the plain DetailsList :)

**Comment by chigivigi** [comment]
Please publish the new nugget version so we can test it in our peoject.

**Comment by vnbaaij** [comment]
Whenever we push to the repository a new version of testable NuGet packages gets build on Azure DevOps. Please see https://github.com/BlazorFluentUI/BlazorFluentUI#dev-nuget-packages on how to enable that for your Visual Studio environement. This way we can get feedback from you all before we publish it more general.

That being said, a 5.3.7 build is on it's way to NuGet now.

**Comment by vnbaaij** [comment]
DetailsList done in 432c98af.
