### ISSUE TITLE
Maui Blazor

### ISSUE THREAD

**Issue by dhindrik** [BlazorFluentUI/BlazorFluentUI#336]
Is it possible to use this for MAUI Blazor? 

I have tried to set it up. But I got an unhandled exception every time I add a component to a page. Unfortunately, I don't know how to see what is going wrong. 

I running preview 5 of both MAUI and .NET 6. And I have tried it on net6.0-ios and net6.0-maccatalyst.

**Comment by limefrogyank** [comment]
I thought the point of MAUI was that you write code once and it generates the ui for each platform automatically. Can you really insert your own controls /components?

Do you have a link to the docs about this? I'd love to figure this out if it's possible...

**Comment by dhindrik** [comment]
It is when you use the hybrid approach with the Blazor WebView.  They also called it Blazor Dekstop for a while. But Right now they seem to call it MAUI Blazor.  You can see more about it in this video, https://www.youtube.com/watch?v=5fbzxjUUKUM

**Comment by limefrogyank** [comment]
So, after playing with it for a little bit, here's what I've discovered:

1.  Very initial stages.  I couldn't get the debugger running on Android.
2. It depends on `Microsoft.AspNetCore.Components.*` 6.0.0-preview packages.  That means all of BlazorFluentUI would have to be upgraded to that version.  Maybe they'll relax that requirement... but not yet.
3. I tried upgrading BlazorFluentUI to dotnet6 and it compiles, but it wouldn't run without errors on Android.  And I couldn't get the debugger to work so I couldn't tell what was wrong.
4. It seems one of the big features is that no internet is required.  But what if you do an HttpRequest?  The microsoft css we use for fonts includes a bunch of http links even if you copy the css file directly.  I tried eliminating all of that and it still didn't work.

So it's really early.  I couldn't get WinUI3 to work on windows even and I followed their instructions.  We'll get there eventually.

**Comment by vnbaaij** [comment]
There is already A. NET 6 branch running on the latest preview. It is under upgrade/net6 branch

**Comment by dhindrik** [comment]
1. I am not able to debug anything related to MAUI on my Mac.

4. I would not say that they have done this to enable it to run offline, the big thing is that you have access to the native API:s. So it will be a hybrid app, with a similar approach as electron.
