### ISSUE TITLE
Vertical NavBar doesn't save its 'IsExpanded' state on rerender.

### ISSUE THREAD

**Issue by Ciwo-K** [BlazorFluentUI/BlazorFluentUI#339]
So I have this navigation on the side of my page.
![image](https://user-images.githubusercontent.com/62892625/124161073-422e8e00-da9d-11eb-9d0a-f5a7761fefaf.png)

I can minimize the first element.
![image](https://user-images.githubusercontent.com/62892625/124161243-743ff000-da9d-11eb-9086-55259cc8e31b.png)

I can click the burger-button to minimize the navigation panel.
![image](https://user-images.githubusercontent.com/62892625/124161138-583c4e80-da9d-11eb-895e-f073739453e4.png)

After reopening the navigation every element is expanded again.
![image](https://user-images.githubusercontent.com/62892625/124161319-8f126480-da9d-11eb-8634-a3161faf2094.png)

**Comment by vnbaaij** [comment]
It is indeed not a super friendly way of interaction but you are correct, state is not being maintaned. You need to keep track of the state yourself.
