### ISSUE TITLE
DetailsList deleting items issues

### ISSUE THREAD

**Issue by horaciodiez** [BlazorFluentUI/BlazorFluentUI#341]
When I delete an item from a DetailsList, removng it from its collection source lile this:
comitenteComerciales.RemoveAll(x => x.ComercialID == selectionComitenteComercial.GetSelection()[0].ComercialID);

1) The next item shows as selected but in the Selection object remains the previous one.
2) So i perform a Selection.ClearSelection(), and then i get this console error:
baseComponent.js:495 Uncaught TypeError: targetToFocusOnNextRepaint.focus is not a function
3) The selection object is clear, nothing is selected in the DetailsList (Ok!) but to select another item, i need to click 3 times on the checkbox in the DetailsList Control.

Anything you need to clarify please ask me for.
Thank you!

**Comment by vnbaaij** [comment]
Hi,
I have the following in one of my programs:
```
<div data-is-scrollable="true" style="height:300px;overflow-y:auto; width:100%">
    <DetailsList ItemsSource="itemList"
                 Columns="Columns"
                 GetKey=@(item=>item.udid)
                 LayoutMode="DetailsListLayoutMode.Justified"
                 TItem="MapDataDetailInfo"
                 OnItemInvoked="OnClick"
                 Selection="Selection"
                 SelectionMode="SelectionMode.Multiple">
    </DetailsList>
</div>

<Stack Horizontal="true" Tokens=@(new StackTokens() { ChildrenGap = new[] { 40.0 } }) Style="margin-top:25px; margin-bottom:25px; width:100%;">
    <StackItem>
        <DefaultButton @onclick="Delete" Disabled="Selection.Count==0">Delete</DefaultButton>
    </StackItem>
</Stack>
```
Then, after making a selection and clicking on 'Delete, I use this:
```
private void Delete()
{
    messages.Clear();

    foreach (MapDataDetailInfo item in Selection.GetSelection())
    {
       //actualcode to delete stuff
        messages.Add($"Data with '{item.udid}' has been deleted");
        itemList.Remove(item);
    }
    Selection.ClearSelection();
    StateHasChanged();
}
```
Observations:
- code is working. Selected rows are being deleted
- if I selecte the 'same' row as deleted one (from an Index perspective), I indeed neet to click three times to select.
- if I select another row, I can select with one click.

Will try to find what is causing this.

**Comment by vnbaaij** [comment]
Ok, I've being trying to find what is causing this, but have not succeeded. What does work in my example is if I exchange the `selection.ClearSelection();` with ` selection = new Selection<DataItem>();`. See https://www.blazorfluentui.net/DetailsListPageBasic for a demo.
