### ISSUE TITLE
Nav css class 'is-selected' is not set on active item

### ISSUE THREAD

**Issue by Ciwo-K** [BlazorFluentUI/BlazorFluentUI#350]
Open this page: https://www.blazorfluentui.net/navPage and click on the first NavLink. The selected NavLink is not highlighted.
![image](https://user-images.githubusercontent.com/62892625/125075023-605c4580-e0be-11eb-9700-8895072f0b35.png)

It should look like this:
![image](https://user-images.githubusercontent.com/62892625/125074984-533f5680-e0be-11eb-99bc-7d410731a534.png)

It seems like the css class is not being updated.

**Comment by vnbaaij** [comment]
The component is getting confused with there being two Nav menu's on the page. If you click open the men uon the left side, you'll see the 'Nav' item being highlighted.
