### ISSUE TITLE
Cleanup BaseComponent

### ISSUE THREAD

**Issue by limefrogyank** [BlazorFluentUI/BlazorFluentUI#37]
- The typescript file is full of functions that aren't sorted in any way.  
- The base directory has no order to it as well.  It's not as bad as the typescript file, but it will be soon.
- There is no guidance on what should be in the BaseComponent project.  Currently, it's just what seems to be available in more than one control...

**Comment by limefrogyank** [comment]
`FocusTrapZone` contains a lot of generic code that needs to be moved to and reference functions in BaseComponent

**Comment by limefrogyank** [comment]
One complication... we don't have a typescript typings definition file.  We have to cast `window` to `any` in order to reference functions from BaseComponent from other components.

**Comment by limefrogyank** [comment]
Added `export` to namespace for BaseComponent (`BlazorFabricBaseComponent`) and then a reference to the component's typescript file.  i.e. 
```
/// <reference path="../../BlazorFabric.BaseComponent/wwwroot/baseComponent.ts" />
```
This seems to make all the exported functions in BaseComponent visible to the other components.  No more using `(<any>window)`

**Comment by limefrogyank** [comment]
Ahhhh, I hate javascript development!!  Anyways, I can't figure out the path changes... When the files are published, all the paths change and the references no longer point to the right files.

**Comment by limefrogyank** [comment]
Yes, that's it.  `BaseComponent` is now generating baseComponent.d.ts in the wwwroot folder.  This must be copied to any new component's wwwroot folder that needs to reference a BaseComponent function and have typings work.  Just add the following to the component typescript file:
```
/// <reference path="baseComponent.d.ts" />

```

**Comment by vnbaaij** [comment]
Now that we are usingproper modules and js isolation, this works differently. See source for working examples
