### ISSUE TITLE
Support for using FluentUI System Icons

### ISSUE THREAD

**Issue by GurliGebis** [BlazorFluentUI/BlazorFluentUI#383]
Reading the installation guide, it mentions using the asset icons with the restrictive license.

Instead, it would be nice if you used this one: https://github.com/microsoft/fluentui-system-icons
It is the same icons, but with the branded icons removed, and with a permissive MIT license, that can be used without the restrictions.

That way, people can use the icons without having to integrate with Microsoft services.

**Comment by limefrogyank** [comment]
Good find. I didn't know they separated them.

Lee McPherson
________________________________
From: GurliGebis ***@***.***>
Sent: Tuesday, August 31, 2021 1:21:25 AM
To: BlazorFluentUI/BlazorFluentUI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BlazorFluentUI/BlazorFluentUI] Support for using FluentUI System Icons (#383)


Reading the installation guide, it mentions using the asset icons with the restrictive license.

Instead, it would be nice if you used this one: https://github.com/microsoft/fluentui-system-icons<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Ffluentui-system-icons&data=04%7C01%7C%7C8e63d9f852924eaaff8708d96c585349%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637659948867108377%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SPUOrrpju56ptENnolhORFJR5jMJC%2Fa5P%2FWq1bS8Hqw%3D&reserved=0>
It is the same icons, but with the branded icons removed, and with a permissive MIT license, that can be used without the restrictions.

That way, people can use the icons without having to integrate with Microsoft services.

**Comment by GurliGebis** [comment]
It isn't that long ago they started doing it, since people complained about them including branded icons that people didn't need, and thereby forcing them to accept the restrictive license.

Another thing that might be worth looking at along with the icons (let me know if I should create another issue for it), is to use the Selawik font instead of the Segoe UI font, since that font is also restrictivly licensed.
The font is an open source replacement for Segoe UI, and can be found here: https://docs.microsoft.com/en-us/typography/font-list/selawik
Here is a ticket on the FluentUI repo regarding it - not sure if it is of any help: https://github.com/microsoft/fluentui/issues/5011

**Comment by scottkuhl** [comment]
I think these are also updated to match the Windows 11 style instead of the older Office style.

**Comment by GurliGebis** [comment]
That would make sense for them to do.

**Comment by vnbaaij** [comment]
I've made an intial start with this in the `fluentsystemicons` branch. Will **definitely** need help with finding the right icons and changing the NavMenu items, etc. 

Result of commits will be pushed to https://white-dune-0ef5c1e03.azurestaticapps.net/

To assit the work needed, I copied over the html file with all the icons from the original repo to FluentSystemIcons page.

Only problem is the site is not working in this branch because of source generator givving errors...

**Comment by limefrogyank** [comment]
When you reference the generator project, you need to add some options to it in the csproj file:

```
<ProjectReference Include="..\BlazorFluentUI.Demo.Generators\BlazorFluentUI.Demo.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
```

**Comment by limefrogyank** [comment]
Question:  Do we hardcode the entire ttf font file into the project or just the icons necessary for the components?  The ttf file is 1.1MB.  

So far, there is no CDN available for this.  But using the actual file would solve using static Blazor inside in an Android or iOS app problem where weblinks are not allowed.

I feel like putting this directly in the project is the right way to go for now.  It makes things very simple for users.

**Comment by vnbaaij** [comment]
I agree with putting it in as best option. Sure, there is the size increase, but it also gives the flexibility of using every icon available. I think we should create a enum/dictionary like there is in `MappedFontIcons.cs` to make it a bit easier for the userss to work with this.

**Comment by limefrogyank** [comment]
I'm noticing that there are multiple sizes of the icons in this font package.  I might try modifying the `Icon` component to specify a non-default size, too.

**Comment by limefrogyank** [comment]
I think it was used in the RowDetail component, but it's useless now.  Maybe we can alias the FontIcon to plain Icon and just create a property for Icon to set filled state.

**Comment by GurliGebis** [comment]
Having the option to include the font file locally would be nice.
I'm currently working on a project where the solution will be run internally, and some of the clients will not be connected to the internet - so having the font loaded from the server instead of a CDN would be a great help.

**Comment by GurliGebis** [comment]
@limefrogyank hasn't this been fixed in the PR you just merged?
And would you like me to create another ticket regarding the Selawik font, so it is possible to use this without having to be bound by the asset license?

**Comment by vnbaaij** [comment]
@GurliGebis you are correct. Closing this one now!

**Comment by GurliGebis** [comment]
Will do :)
