### ISSUE TITLE
Blazor Server Demo Web App is Stopped

### ISSUE THREAD

**Issue by v-rusmit** [BlazorFluentUI/BlazorFluentUI#384]
I'm getting this error when trying to use https://blazorfluentui.azurewebsites.net/ Error 403 - This web app is stopped. I was using this site for code examples while the other one has issues displaying code.

**Comment by limefrogyank** [comment]
It's on a free azure instance and probably hit the monthly limit.

Lee McPherson
________________________________
From: Russell Smith ***@***.***>
Sent: Wednesday, September 1, 2021 4:08:15 PM
To: BlazorFluentUI/BlazorFluentUI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BlazorFluentUI/BlazorFluentUI] Blazor Server Demo Web App is Stopped (#384)


I'm getting this error when trying to use https://blazorfluentui.azurewebsites.net/<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblazorfluentui.azurewebsites.net%2F&data=04%7C01%7C%7C84ad384d299c4fc1e59608d96d9d6156%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637661344974623175%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LWWV%2B8gIj74QYfVq3DqxwAB5SQnlH%2F9KooKIibCNRFM%3D&reserved=0> Error 403 - This web app is stopped. I was using this site for code examples while the other one has issues displaying code.

**Comment by vnbaaij** [comment]
Site is working again now
