### ISSUE TITLE
DetailListAuto sort not working

### ISSUE THREAD

**Issue by chigivigi** [BlazorFluentUI/BlazorFluentUI#385]
I would like the issue DetailListAuto sort column not triggered on click -  
 https://github.com/BlazorFluentUI/BlazorFluentUI/issues/366 to be reopened.

The method described did not help in solving the problem and the entire page broke after running it locally.
I copied the error message and written code snippets for the model and column details used. The name of the model and properties have been changed but everything else is the same.

**Comment by vnbaaij** [comment]
Original issue is reopened. Closing this one
