### ISSUE TITLE
Modal is broken on .net 6

### ISSUE THREAD

**Issue by Valks** [BlazorFluentUI/BlazorFluentUI#388]
Using .net 6 preview 7 The ```<Modal>``` control isn't showing when setting IsOpen to ```true``` (or even if it's set to ```true``` by default).

I've tried the latest (and preview) builds and the V6 release: https://github.com/BlazorFluentUI/BlazorFluentUI/releases/tag/V6-preview6

The only output generated is the HTML comment tags that Blazor creates as placeholders.

**Comment by vnbaaij** [comment]
There is a .NET 6 version available at https://white-dune-0ef5c1e03.azurestaticapps.net/modalPage. Modal is working as expected.
