### ISSUE TITLE
<Text> element usage issue

### ISSUE THREAD

**Issue by ahussain-vasont** [BlazorFluentUI/BlazorFluentUI#398]
When I added `<Text Variant="">Some text</Text>` to a .razor page it complained about 

> `<text>` and `</text>` tags cannot contain attributes

I guess since `<text>` is Razor's own it's complaining? Anyone overcame this issue?

**Comment by vnbaaij** [comment]
Use the full 'namespace' to make it more specific e.g. `<BlazorFluentUI.Text>`
