### ISSUE TITLE
Invalid behavior for Dialog, Modal, Panel and Tooltip components and issue with Scrolling

### ISSUE THREAD

**Issue by makmilind** [BlazorFluentUI/BlazorFluentUI#404]
Hello,

I am finding inconsistent and/or incorrect behavior with `Dialog`, `Modal`, `Panel` and `Tooltip` components, which in turn is creating issue for scrolling.
BlazorFluentUI Version: I am using 5.7.5 but seeing the same behavior in 6.0.0 in the demo site.
I recently migrated to 5.7.5 version and now I have started seeing these behavioral issues with above mentioned components.

**Issue Description:**
- The `Dialog`, `Modal`, and `Panel` components are not freezing the background layer.
- Scrollbar of the background layer is still visible when either of the components are opened.
- This allows the background layer to be scrollable through freely while the any of the above three components are open.
- As the scrollbar of the background layer is still visible, it overrides the visible scrollbar for `Panel` component when `Panel` component has its own scrollable content.
- On the `Tooltip` component, when hovered over and after the tooltip opens, if we scroll the window, the Tooltip window/panel moves along with the mouse pointer
- Also, there is an intermittent error with `Tooltip` window/panel, it gets stuck with the main window/panel layer and won't disappear until the page/site is completely refreshed.

**Components in demo site:**
- [Dialog component](https://www.blazorfluentui.net/dialogPage)
- [Modal component](https://www.blazorfluentui.net/modalPage)
- [Panel component](https://www.blazorfluentui.net/panelPage)
- [Tooltip component](https://www.blazorfluentui.net/tooltipPage)

**For comparing behaviors, please see their original counterparts i.e. react FluentUI components:**
- [Dialog component](https://developer.microsoft.com/en-us/fluentui#/controls/web/dialog)
- [Modal component](https://developer.microsoft.com/en-us/fluentui#/controls/web/modal)
- [Panel component](https://developer.microsoft.com/en-us/fluentui#/controls/web/panel)
- [Tooltip component](https://developer.microsoft.com/en-us/fluentui#/controls/web/tooltip)

Note: I added the original counterparts to see the correct behavior but the BlazorFluentUI components were behaving correctly previously i.e. in older version, before I migrated to 5.7.5

I know this component library is now under low maintenance so I understand that the updates/fixes are going to be rare but I would really like to see this get fixed or at least get some kind of temporary work around solution for this, which I can add it on my end. I'd really appreciate it if someone can help with this issue.

Please let me know in case any additional information is needed.
Thank you

**Comment by vnbaaij** [comment]
There was indeed an issue with the overlay component introduced in 5.6.0. Reverted this change and am publishing 6.0.1 now

**Comment by makmilind** [comment]
Thank you for the quick update. I really appreciate it!

**Comment by makmilind** [comment]
@vnbaaij oh I just realized the fix got added into .NET 6 version of the package. Unfortunately, I am not able to add this fix into my project currently as the fix was added into .NET 6 version of the package and my project is still using .NET 5. It seems updating the package from 5.7.5 to 6.0.1 gives bunch of errors in my project so it is not possible for me to move to 6.0.1 right now since it requires us to migrate whole project to .NET 6 that would mean, it will require us to migrate all of the libraries and changes to use .NET 6 right now.

Is there a way I can add this fix manually for the 5.7.5 version of the package?
Please let me know if there is any possible workaround solution for this.

Thanks!

**Comment by vnbaaij** [comment]
@makmilind You should definitely upgrade to .NET 6 as soon as possible. You will get free performance upgrade across the board and .NET 5will go out of support in about 6 months time. .NET 6 is a Long Term Support (LTS) release.
If you are seeing a lot of errors, then there is something wrong in you project probably. It should be mostly backwards compatible.

I'll see if can do a 5.7.6 release but that will definitely be the last release on .NET 5.

**Comment by vnbaaij** [comment]
v5,7,6 is available on NuGet now

**Comment by makmilind** [comment]
@vnbaaij thank you for making this update release to 5.x version. I really appreciate it. I'll definitely try to upgrade my project to .NET 6 but since we had a launch coming in next week i.e. before thanksgiving break and with all the pipelines already setup to support .NET 5, it would have required us bit of regression-testing for any issues but I am certainly planning to upgrade my project to .NET 6 as you suggested.

Regarding the errors, just my guess since you said it is backwards compatible, I think when I tried updating the package to 6.0.1, it may have also required to upgrade other packages along with BlazorFluentUI library I assume.
For some odd reason I could not import library with the `using` statement as it kept telling me that `BlazorFluentUI` namespace could not be found. I probably missed something so I may investigate more, I'll post my findings here in case I investigate and find something. But anyhow I am planning to upgrade the project to .NET 6 sometime around next month so I may skip the investigation on that issue.
