### ISSUE TITLE
Fix Demo Server Side

### ISSUE THREAD

**Issue by Ciwo-K** [BlazorFluentUI/BlazorFluentUI#406]
I can't start the server demo after cloning this repo.
Error message:
![image](https://user-images.githubusercontent.com/62892625/142390117-46d2e9ee-4c7b-4041-bf15-3f6f03db3690.png)

**Comment by vnbaaij** [comment]
Yeah, there is something strange with that package. Find the `System.Reactive.dll` on your system (or download the package and use NuGet package explorer to extract it) and copy it to the `/bin{debug or release}/net6.0` folder of the Server demo. It should work then
