### ISSUE TITLE
Colon in Label-text on special occasion

### ISSUE THREAD

**Issue by RAN-Vestjylland** [BlazorFluentUI/BlazorFluentUI#411]
I would like that when you set a Label, colon is not set automatically. I would prefer to 100% control what my label text is when I set it.

**Comment by vnbaaij** [comment]
Where are you seeing this happening?

**Comment by RAN-Vestjylland** [comment]
I've had to make some kind of auto complete dropdown thing using the text field. That is not what causes the issue. And I use the underline parameter set to true.
![2022-03-17 08_01_19-Window](https://user-images.githubusercontent.com/78351622/158754944-198b83c1-e3b6-40c9-bdcc-e81d8e65b56b.png)
Then I use the auto complete component I made like this (here you can see I don't have any colons set in the label parameter.
![2022-03-17 08_02_37-Window](https://user-images.githubusercontent.com/78351622/158755007-91f21815-9e57-4955-85ca-1b647eaeddd6.png)
And this is how it looks when running the website:
![2022-03-17 08_01_55-Henrik Stokvad -](https://user-images.githubusercontent.com/78351622/158755061-6d4002af-48b5-4211-81ac-6cd4ed32ee3c.png)
When I remove the part setting the underline parameter the style looks a bit weird but then the colons are gone! And I'm not having a colon set on ::after because I use the textfield component other places, and there is not any colon set.
![2022-03-17 08_03_19-Window](https://user-images.githubusercontent.com/78351622/158755245-2da573e5-9fe9-4f99-a516-161e83d68409.png)
And this is how it looks like when running the website:
![2022-03-17 08_04_31-Henrik Stokvad -](https://user-images.githubusercontent.com/78351622/158755277-81941411-41e6-46eb-b1a3-6980216e6dcf.png)

**Comment by RAN-Vestjylland** [comment]
@vnbaaij I'm curious, if you are trying to figure this out? :-) Thank you in advance!

**Comment by vnbaaij** [comment]
Yes, hope to have time for this this week. Will keep you posted
