### ISSUE TITLE
Build error In Visual Studio 2019

### ISSUE THREAD

**Issue by intto77** [BlazorFluentUI/BlazorFluentUI#413]
Hi

I have a problems

I build this solution and cause erros..

May I know why the build error is coming out?

Use : 
 dotnet  6.0
 visual studio 2019 

![image](https://user-images.githubusercontent.com/97278496/162915037-90e52036-1824-4df3-a657-1ca9265ae618.png)

**Comment by vnbaaij** [comment]
.NET 6 on Visual Studio 2019 is not supported: 
![image](https://user-images.githubusercontent.com/1761079/162932028-1b5ce7d2-eaca-4e6b-a4f8-12ad7c929891.png)
 Therefore won't investigate this further.
