### ISSUE TITLE
RichTextEditor command bar hidden

### ISSUE THREAD

**Issue by LucaCris** [BlazorFluentUI/BlazorFluentUI#419]
Working, but **not visible**:

![immagine](https://github.com/BlazorFluentUI/BlazorFluentUI/assets/50824617/44a93c94-d52d-4242-ad8c-41ada8f037b1)

Tested in Edge and Firefox, same problem.

**Comment by vnbaaij** [comment]
This library is in maintenance mode. Code has not been updated for a long time. I suggest you switch to the [Fluent UI Blazor library](https://github.com/microsoft/fluentui-blazor/) (which does not have a Rich Text Editor btw)
