### ISSUE TITLE
Rating doesn't automatically change when using keyboard navigation

### ISSUE THREAD

**Issue by limefrogyank** [BlazorFluentUI/BlazorFluentUI#43]
Not sure if this is really necessary.  

The original React control will update the value of the `Rating` when navigating using the keyboard.  In our current version of the control, you can navigate the control with the keyboard, but you need to push spacebar to make the value of the `Rating` change.

Should we make it like the React control or leave it alone?

**Comment by vnbaaij** [comment]
Navigating / Selecting with keyboard arrows works now. Added in #054d92b
