### ISSUE TITLE
Implement MaskTextField Component

### ISSUE THREAD

**Issue by Eweol** [BlazorFluentUI/BlazorFluentUI#51]
Second Part of [#30](https://github.com/limefrogyank/BlazorFabric/issues/30)

**Comment by RAN-Vestjylland** [comment]
Does "MaskTextField" mean that the mask can be set to only be able to for instance type in numbers as int, long, double, float etc. as well? I mean a problem I'm having is that (in v4.0.3) I can't bind an int to the BFUTextField. The component complains that the property in the model is not a string.

**Comment by NPadrutt** [comment]
I think this more means input masks like this from the react fluentUI Demo page:
![image](https://user-images.githubusercontent.com/1764367/112477397-41d27880-8d73-11eb-9a10-d903cfe884e5.png)

**Comment by RAN-Vestjylland** [comment]
I think I need to suggest a new control that supports binding of numbers. I had the feeling that it was "only" that type of input-mask.

**Comment by vnbaaij** [comment]
The component binding to numbers is done in TextFieldNumber. Mask needs to be worked on. I see in React this is a seperate control MaskedTextField. Makes sense to do the same here.
Following that logic, I'll rename TextFielNumber to NumberTextField
