### ISSUE TITLE
Calendar with min/max dates will show disabled selection in monthPicker 

### ISSUE THREAD

**Issue by limefrogyank** [BlazorFluentUI/BlazorFluentUI#60]
To reproduce, create a `Calendar` with a min/max set of dates so that many months are disabled.  Use the year spinbuttons in the month picker to shift the year up or down.  If your currently selected month in one year is enabled, that same month in a year where it is disabled will still be shown as selected.  

This is just a UI problem and does not interfere with the function of the `Calendar`.

**Comment by limefrogyank** [comment]
![image](https://user-images.githubusercontent.com/7821384/69904722-c8816c00-135e-11ea-87e4-93be4166ec26.png)

**Comment by vnbaaij** [comment]
As far as I can see, this works correct now.
