### ISSUE TITLE
WASM Calendar Today defaults to GMT (0 offset)

### ISSUE THREAD

**Issue by limefrogyank** [BlazorFluentUI/BlazorFluentUI#63]

**Comment by limefrogyank** [comment]
![image](https://user-images.githubusercontent.com/7821384/69909183-0658b180-13ac-11ea-8908-562730247d50.png)

**Comment by limefrogyank** [comment]
ServerSide works fine:

![image](https://user-images.githubusercontent.com/7821384/69909227-82eb9000-13ac-11ea-9530-b63e86143534.png)

**Comment by limefrogyank** [comment]
Mono issue:  https://github.com/mono/mono/issues/15260

**Comment by limefrogyank** [comment]
workaround here:  https://dev.to/j_sakamoto/workaround-how-to-resolve-local-time-zone-on-blazor-spa-v05x-foi

However, I may just dive into how they do it and put it in the control directly.

**Comment by limefrogyank** [comment]
Nevermind, this is a Mono bug (lack of support).  They're going to fix it by the official client-side Blazor release.  We'll just have this as a dependency if you want timezones to work properly.  

Just in case the website disappears:

1.  Install Nuget package `Toolbelt.Blazor.TimeZoneKit` into wasm Blazor app project.
2.  Change your Startup.cs to the following:
```
using Toolbelt.Blazor.Extensions.DependencyInjection;

//namespace ...
public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
        }

        public void Configure(IComponentsApplicationBuilder app)
        {
            app.UseLocalTimeZone();
            app.AddComponent<App>("app");
        }
    }
```

**Comment by limefrogyank** [comment]
Might as well leave it open until we know it's been fixed.

**Comment by richbryant** [comment]
I don't see what the problem is :)

**Comment by limefrogyank** [comment]
I believe this has been fixed by mono.
